// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "ESQLDumpPipeline.h"
#include "Core/ESQLDatabase.h"
#include "UnrealExtendedSQL.h"
#include "HAL/PlatformFileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"


// ── Export ────────────────────────────────────────────────────────────────────

bool FESQLDumpPipeline::ExportDatabaseToDump(
	TSharedPtr<FESQLDatabase> Database,
	const FString& DumpFilePath,
	FString& OutError)
{
	if (!Database || !Database->IsOpen())
	{
		OutError = TEXT("Database is not open");
		return false;
	}

	FString DumpContent;

	// Header
	DumpContent += TEXT("-- ExtendedSQL Database Dump\n");
	DumpContent += TEXT("-- Generated by UnrealExtendedSQL\n");
	DumpContent += FString::Printf(TEXT("-- Timestamp: %s\n"), *FDateTime::UtcNow().ToIso8601());
	DumpContent += TEXT("-- This file is the VCS source of truth. .db files are derived.\n");
	DumpContent += TEXT("\n");

	// Get list of all user tables (skip sqlite_* internal tables)
	FESQLQueryResult TablesResult = Database->Execute(
		TEXT("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"));

	if (!TablesResult.bSuccess)
	{
		OutError = FString::Printf(TEXT("Failed to query tables: %s"), *TablesResult.ErrorMessage);
		return false;
	}

	for (const FESQLRow& TableRow : TablesResult.Rows)
	{
		FString TableName;
		FString CreateSQL;

		if (!TableRow.TryGetString(TEXT("name"), TableName) || !TableRow.TryGetString(TEXT("sql"), CreateSQL))
		{
			continue;
		}

		// Write CREATE TABLE (with IF NOT EXISTS for safety)
		FString SafeCreateSQL = CreateSQL;
		if (!SafeCreateSQL.Contains(TEXT("IF NOT EXISTS"), ESearchCase::IgnoreCase))
		{
			SafeCreateSQL = SafeCreateSQL.Replace(TEXT("CREATE TABLE"), TEXT("CREATE TABLE IF NOT EXISTS"));
		}
		DumpContent += SafeCreateSQL + TEXT(";\n\n");

		// Get all rows for this table, sorted by first column (usually PK) for deterministic diffs
		FESQLQueryResult ColumnsResult = Database->Execute(
			FString::Printf(TEXT("PRAGMA table_info(\"%s\")"), *TableName));

		if (!ColumnsResult.bSuccess || !ColumnsResult.HasRows()) continue;

		// Get the first column name for ORDER BY (deterministic sorting)
		FString FirstColumnName;
		TArray<FString> ColumnNames;
		for (const FESQLRow& ColRow : ColumnsResult.Rows)
		{
			FString ColName;
			if (ColRow.TryGetString(TEXT("name"), ColName))
			{
				ColumnNames.Add(ColName);
				if (FirstColumnName.IsEmpty())
				{
					FirstColumnName = ColName;
				}
			}
		}

		// Query all rows sorted by PK
		FString SelectSQL = FString::Printf(TEXT("SELECT * FROM \"%s\" ORDER BY \"%s\""),
			*TableName, *FirstColumnName);
		FESQLQueryResult RowsResult = Database->Execute(SelectSQL);

		if (!RowsResult.bSuccess || !RowsResult.HasRows())
		{
			DumpContent += FString::Printf(TEXT("-- (empty table: %s)\n\n"), *TableName);
			continue;
		}

		// Write INSERT OR REPLACE for each row
		for (const FESQLRow& Row : RowsResult.Rows)
		{
			FString ColList;
			FString ValueList;
			bool bFirst = true;

			for (const FString& ColName : ColumnNames)
			{
				if (!bFirst) { ColList += TEXT(", "); ValueList += TEXT(", "); }

				ColList += FString::Printf(TEXT("\"%s\""), *ColName);

				if (Row.IsNull(ColName))
				{
					ValueList += TEXT("NULL");
				}
				else
				{
					const FString Value = Row.FindValue(ColName) ? *Row.FindValue(ColName) : FString();
					FString EscapedValue = Value.Replace(TEXT("'"), TEXT("''"));
					ValueList += FString::Printf(TEXT("'%s'"), *EscapedValue);
				}

				bFirst = false;
			}

			DumpContent += FString::Printf(TEXT("INSERT OR REPLACE INTO \"%s\" (%s) VALUES (%s);\n"),
				*TableName, *ColList, *ValueList);
		}

		DumpContent += TEXT("\n");
	}

	// Also dump indexes
	FESQLQueryResult IndexResult = Database->Execute(
		TEXT("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"));

	if (IndexResult.bSuccess && IndexResult.Rows.Num() > 0)
	{
		DumpContent += TEXT("-- Indexes\n");
		for (const FESQLRow& IdxRow : IndexResult.Rows)
		{
			FString IdxSQL;
			if (IdxRow.TryGetString(TEXT("sql"), IdxSQL))
			{
				if (!IdxSQL.IsEmpty())
				{
					// Add IF NOT EXISTS for safety
					FString SafeIdxSQL = IdxSQL;
					if (!SafeIdxSQL.Contains(TEXT("IF NOT EXISTS"), ESearchCase::IgnoreCase))
					{
						SafeIdxSQL = SafeIdxSQL.Replace(TEXT("CREATE INDEX"), TEXT("CREATE INDEX IF NOT EXISTS"));
						SafeIdxSQL = SafeIdxSQL.Replace(TEXT("CREATE UNIQUE INDEX"), TEXT("CREATE UNIQUE INDEX IF NOT EXISTS"));
					}
					DumpContent += SafeIdxSQL + TEXT(";\n");
				}
			}
		}
		DumpContent += TEXT("\n");
	}

	// Ensure directory exists
	const FString Directory = FPaths::GetPath(DumpFilePath);
	if (!Directory.IsEmpty())
	{
		IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
		if (!PlatformFile.DirectoryExists(*Directory))
		{
			PlatformFile.CreateDirectoryTree(*Directory);
		}
	}

	if (!FFileHelper::SaveStringToFile(DumpContent, *DumpFilePath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		OutError = FString::Printf(TEXT("Failed to write .sqldump to: %s"), *DumpFilePath);
		return false;
	}

	UE_LOG(LogExtendedSQL, Log, TEXT("Exported .sqldump: %s (%d tables)"),
		*DumpFilePath, TablesResult.Rows.Num());

	return true;
}


// ── Import ───────────────────────────────────────────────────────────────────

bool FESQLDumpPipeline::ImportDumpToDatabase(
	TSharedPtr<FESQLDatabase> Database,
	const FString& DumpFilePath,
	FString& OutError)
{
	if (!Database || !Database->IsOpen())
	{
		OutError = TEXT("Database is not open");
		return false;
	}

	FString DumpContent;
	if (!FFileHelper::LoadFileToString(DumpContent, *DumpFilePath))
	{
		OutError = FString::Printf(TEXT("Failed to read .sqldump: %s"), *DumpFilePath);
		return false;
	}

	TArray<FString> Statements = ParseDumpStatements(DumpContent);

	if (Statements.Num() == 0)
	{
		UE_LOG(LogExtendedSQL, Warning, TEXT("Empty .sqldump file: %s"), *DumpFilePath);
		return true; // Not an error — just nothing to import
	}

	// Temporarily disable FK checks during import — the dump's table/insert order
	// may not respect FK dependencies (e.g. alphabetical export: cities before regions).
	// This is the standard approach used by SQLite's .dump and other tools.
	Database->Execute(TEXT("PRAGMA foreign_keys=OFF"));

	Database->BeginTransaction();

	int32 SuccessCount = 0;
	for (const FString& Statement : Statements)
	{
		FESQLQueryResult Result = Database->Execute(Statement);
		if (!Result.bSuccess)
		{
			Database->RollbackTransaction();
			Database->Execute(TEXT("PRAGMA foreign_keys=ON"));
			OutError = FString::Printf(TEXT("Failed to execute statement: %s\nError: %s"),
				*Statement, *Result.ErrorMessage);
			return false;
		}
		++SuccessCount;
	}

	Database->CommitTransaction();

	// Re-enable FK checks
	Database->Execute(TEXT("PRAGMA foreign_keys=ON"));

	UE_LOG(LogExtendedSQL, Log, TEXT("Imported .sqldump: %s (%d statements)"),
		*DumpFilePath, SuccessCount);

	return true;
}


// ── Bidirectional Sync ───────────────────────────────────────────────────────

bool FESQLDumpPipeline::SyncDatabaseAndDump(
	const FString& DatabasePath,
	const FString& DumpPath,
	FString& OutError)
{
	IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();

	const bool bDbExists = PlatformFile.FileExists(*DatabasePath);
	const bool bDumpExists = PlatformFile.FileExists(*DumpPath);

	if (!bDbExists && !bDumpExists)
	{
		// Neither exists — nothing to sync
		return true;
	}

	if (!bDbExists && bDumpExists)
	{
		// .db missing, .sqldump exists → rebuild .db from .sqldump
		UE_LOG(LogExtendedSQL, Log, TEXT("Sync: .db missing, rebuilding from .sqldump"));
		return RebuildDatabaseFromDump(DumpPath, DatabasePath, OutError);
	}

	if (bDbExists && !bDumpExists)
	{
		// .db exists, no .sqldump → export .sqldump from .db
		UE_LOG(LogExtendedSQL, Log, TEXT("Sync: .sqldump missing, exporting from .db"));
		FString DbError;
		TSharedPtr<FESQLDatabase> Database = FESQLDatabase::Open(DatabasePath, DbError);
		if (!Database)
		{
			OutError = DbError;
			return false;
		}

		bool bResult = ExportDatabaseToDump(Database, DumpPath, OutError);
		Database->Close();
		return bResult;
	}

	// Both exist — compare timestamps
	const FDateTime DbTimestamp = PlatformFile.GetTimeStamp(*DatabasePath);
	const FDateTime DumpTimestamp = PlatformFile.GetTimeStamp(*DumpPath);

	if (DumpTimestamp > DbTimestamp)
	{
		// .sqldump is newer → rebuild .db from .sqldump
		UE_LOG(LogExtendedSQL, Log, TEXT("Sync: .sqldump is newer, rebuilding .db"));
		return RebuildDatabaseFromDump(DumpPath, DatabasePath, OutError);
	}
	else if (DbTimestamp > DumpTimestamp)
	{
		// .db is newer → re-export .sqldump from .db
		UE_LOG(LogExtendedSQL, Log, TEXT("Sync: .db is newer, re-exporting .sqldump"));
		FString DbError;
		TSharedPtr<FESQLDatabase> Database = FESQLDatabase::Open(DatabasePath, DbError);
		if (!Database)
		{
			OutError = DbError;
			return false;
		}

		bool bResult = ExportDatabaseToDump(Database, DumpPath, OutError);
		Database->Close();
		return bResult;
	}
	else
	{
		// Same timestamp — .sqldump is authoritative, rebuild .db to be safe
		UE_LOG(LogExtendedSQL, Log, TEXT("Sync: Timestamps match, rebuilding .db from .sqldump (safe default)"));
		return RebuildDatabaseFromDump(DumpPath, DatabasePath, OutError);
	}
}


// ── Path Helpers ─────────────────────────────────────────────────────────────

FString FESQLDumpPipeline::GetDumpPathForDatabase(const FString& DatabasePath)
{
	return FPaths::ChangeExtension(DatabasePath, TEXT(".sqldump"));
}

FString FESQLDumpPipeline::GetDatabasePathForDump(const FString& DumpPath)
{
	return FPaths::ChangeExtension(DumpPath, TEXT(".db"));
}


// ── Cook Pipeline ────────────────────────────────────────────────────────────

bool FESQLDumpPipeline::RebuildDatabaseFromDump(
	const FString& DumpPath,
	const FString& OutputDbPath,
	FString& OutError)
{
	IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();

	// Delete existing .db and WAL/SHM files for a clean rebuild
	if (PlatformFile.FileExists(*OutputDbPath))
	{
		PlatformFile.DeleteFile(*OutputDbPath);
	}
	PlatformFile.DeleteFile(*(OutputDbPath + TEXT("-wal")));
	PlatformFile.DeleteFile(*(OutputDbPath + TEXT("-shm")));

	// Open a fresh database
	FString DbError;
	TSharedPtr<FESQLDatabase> Database = FESQLDatabase::Open(OutputDbPath, DbError);
	if (!Database)
	{
		OutError = FString::Printf(TEXT("Failed to create fresh database: %s"), *DbError);
		return false;
	}

	// Import the dump
	bool bResult = ImportDumpToDatabase(Database, DumpPath, OutError);
	Database->Close();

	if (bResult)
	{
		UE_LOG(LogExtendedSQL, Log, TEXT("Rebuilt .db from .sqldump: %s → %s"), *DumpPath, *OutputDbPath);
	}

	return bResult;
}

FString FESQLDumpPipeline::GetGitIgnoreRecommendation()
{
	return TEXT(
		"# ExtendedSQL — .db files are derived from .sqldump (VCS source of truth)\n"
		"# .sqldump files SHOULD be committed to version control\n"
		"*.db\n"
		"*.db-wal\n"
		"*.db-shm\n"
	);
}


// ── Statement Parser ─────────────────────────────────────────────────────────

TArray<FString> FESQLDumpPipeline::ParseDumpStatements(const FString& DumpContent)
{
	TArray<FString> Statements;
	FString CurrentStatement;

	TArray<FString> Lines;
	DumpContent.ParseIntoArrayLines(Lines);

	for (const FString& Line : Lines)
	{
		FString TrimmedLine = Line.TrimStartAndEnd();

		// Skip empty lines and comments
		if (TrimmedLine.IsEmpty()) continue;
		if (TrimmedLine.StartsWith(TEXT("--"))) continue;

		CurrentStatement += Line + TEXT("\n");

		// Check if statement is complete (ends with semicolon)
		if (TrimmedLine.EndsWith(TEXT(";")))
		{
			FString FinalStatement = CurrentStatement.TrimStartAndEnd();
			// Remove trailing semicolon for sqlite3_prepare_v2 (it only compiles one statement)
			if (FinalStatement.EndsWith(TEXT(";")))
			{
				FinalStatement.LeftChopInline(1);
			}
			FinalStatement.TrimEndInline();

			if (!FinalStatement.IsEmpty())
			{
				Statements.Add(FinalStatement);
			}
			CurrentStatement.Empty();
		}
	}

	// Handle any remaining unterminated statement
	if (!CurrentStatement.TrimStartAndEnd().IsEmpty())
	{
		FString FinalStatement = CurrentStatement.TrimStartAndEnd();
		if (FinalStatement.EndsWith(TEXT(";")))
		{
			FinalStatement.LeftChopInline(1);
			FinalStatement.TrimEndInline();
		}
		if (!FinalStatement.IsEmpty())
		{
			Statements.Add(FinalStatement);
		}
	}

	return Statements;
}
