// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "K2Node/ESQLTypedRowK2Nodes.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node/ESQLK2FieldFilterUtils.h"
#include "K2Node/ESQLRuntimeReflectionUtils.h"
#include "K2Node_CallFunction.h"
#include "K2Node_Self.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Misc/OutputDeviceNull.h"
#include "Shared/ESQLId.h"
#include "Styling/AppStyle.h"
#include "TableAsset/ESQLTableAsset.h"
#include "UObject/PropertyPortFlags.h"

#define LOCTEXT_NAMESPACE "ESQLTypedRowK2Nodes"

namespace ESQLTypedRowK2NodePins
{
	const FName WorldContextObject(TEXT("WorldContextObject"));
	const FName TableAsset(TEXT("TableAsset"));
	const FName RowId(TEXT("RowId"));
	const FName SqlId(TEXT("SqlId"));
	const FName OutRow(TEXT("OutRow"));
	const FName RowData(TEXT("RowData"));
	const FName RowIdOverride(TEXT("RowIdOverride"));
	const FName OutResolvedRowId(TEXT("OutResolvedRowId"));
	const FName Result(TEXT("Result"));
	const FName FieldName(TEXT("FieldName"));
	const FName Operation(TEXT("Operation"));
	const FName Value(TEXT("Value"));
}

namespace
{
	bool ShouldRegisterBlueprintAction(const UClass* NodeClass)
	{
		return NodeClass && !NodeClass->HasMetaData(TEXT("ESQLHideFromBlueprintPalette"));
	}

	const UEdGraphPin* FindPinByName(const TArray<UEdGraphPin*>& PinsToSearch, const FName PinName)
	{
		for (const UEdGraphPin* Pin : PinsToSearch)
		{
			if (Pin && Pin->PinName == PinName)
			{
				return Pin;
			}
		}

		return nullptr;
	}

	UScriptStruct* ExtractStructTypeFromPin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.ContainerType != EPinContainerType::None)
		{
			return nullptr;
		}

		if (Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
		{
			return nullptr;
		}

		return Cast<UScriptStruct>(Pin->PinType.PinSubCategoryObject.Get());
	}

	bool IsESQLIdStructPin(const UEdGraphPin* Pin)
	{
		const UScriptStruct* PinStruct = ExtractStructTypeFromPin(Pin);
		const UScriptStruct* SqlIdStruct = FESQLId::StaticStruct();
		return PinStruct
			&& SqlIdStruct
			&& (PinStruct == SqlIdStruct || PinStruct->GetName().Contains(SqlIdStruct->GetName(), ESearchCase::IgnoreCase));
	}

	void MoveOrCopyPinToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	}

	UK2Node_CallFunction* SpawnSQLSubsystemGetterNode(FKismetCompilerContext& CompilerContext, UK2Node& SourceNode, UEdGraph* SourceGraph, UEdGraphPin* WorldContextPin)
	{
		static const FName ContextObjectPinName(TEXT("ContextObject"));
		static const FName ClassPinName(TEXT("Class"));

		UK2Node_CallFunction* GetSubsystemNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(&SourceNode, SourceGraph);
		ESQLRuntimeReflectionUtils::BindGameInstanceSubsystemGetter(*GetSubsystemNode);
		GetSubsystemNode->AllocateDefaultPins();

		UEdGraphPin* GetterWorldContextPin = GetSubsystemNode->FindPinChecked(ContextObjectPinName);
		if (WorldContextPin && WorldContextPin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*WorldContextPin, *GetterWorldContextPin);
		}
		else if (WorldContextPin && WorldContextPin->DefaultObject)
		{
			GetterWorldContextPin->DefaultObject = WorldContextPin->DefaultObject;
		}
		else
		{
			UK2Node_Self* SelfNode = CompilerContext.SpawnIntermediateNode<UK2Node_Self>(&SourceNode, SourceGraph);
			SelfNode->AllocateDefaultPins();
			SelfNode->FindPinChecked(UEdGraphSchema_K2::PN_Self)->MakeLinkTo(GetterWorldContextPin);
		}

		UEdGraphPin* GetterClassPin = GetSubsystemNode->FindPinChecked(ClassPinName);
		GetterClassPin->DefaultObject = UESQLSubsystem::StaticClass();

		UEdGraphPin* GetterResultPin = GetSubsystemNode->GetReturnValuePin();
		GetterResultPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Object;
		GetterResultPin->PinType.PinSubCategory = NAME_None;
		GetterResultPin->PinType.PinSubCategoryObject = UESQLSubsystem::StaticClass();
		return GetSubsystemNode;
	}

	void MoveFieldFilterPinsToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node* SourceNode, UK2Node_CallFunction* FunctionNode)
	{
		MoveOrCopyPinToIntermediate(CompilerContext, SourceNode->FindPinChecked(ESQLTypedRowK2NodePins::FieldName), FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::FieldName));
		MoveOrCopyPinToIntermediate(CompilerContext, SourceNode->FindPinChecked(ESQLTypedRowK2NodePins::Operation), FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::Operation));
		ESQLK2FieldFilterUtils::MoveValuePinToBindingPin(CompilerContext, SourceGraph, SourceNode, SourceNode->FindPinChecked(ESQLTypedRowK2NodePins::Value), FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::Value));
	}

	void RefreshFieldValuePinType(UK2Node* Node)
	{
		if (UEdGraphPin* ValuePin = Node ? Node->FindPin(ESQLTypedRowK2NodePins::Value) : nullptr)
		{
			ESQLK2FieldFilterUtils::ApplyFieldValuePinType(*ValuePin, ESQLK2FieldFilterUtils::ResolveLiteralFieldProperty(Node, ESQLTypedRowK2NodePins::TableAsset, ESQLTypedRowK2NodePins::FieldName));
		}
	}

	bool TryGetSqlIdFromStructDefault(const UEdGraphPin* Pin, FESQLId& OutSqlId)
	{
		OutSqlId = FESQLId();
		if (!Pin
			|| Pin->LinkedTo.Num() > 0
			|| !IsESQLIdStructPin(Pin))
		{
			return false;
		}

		const FString DefaultValue = Pin->GetDefaultAsString();
		if (DefaultValue.IsEmpty())
		{
			return false;
		}

		FOutputDeviceNull NullOutput;
		FESQLId::StaticStruct()->ImportText(*DefaultValue, &OutSqlId, nullptr, PPF_SerializedAsImportText, &NullOutput, Pin->PinName.ToString());
		return !OutSqlId.Value.IsEmpty();
	}
}

void UK2Node_ESQLTypedRowSubsystemBase::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* WorldContextPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), ESQLTypedRowK2NodePins::WorldContextObject);
	WorldContextPin->PinFriendlyName = LOCTEXT("WorldContextFriendlyName", "World Context");
	SetPinToolTip(*WorldContextPin, LOCTEXT("WorldContextTooltip", "Runtime world context used to initialize and query the SQL table asset."));

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLTypedRowK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("TableAssetFriendlyName", "Table Asset");
	SetPinToolTip(*TableAssetPin, LOCTEXT("TableAssetTooltip", "The SQL table asset that owns the row struct and query behavior."));

	AllocateOperationPins();

	UEdGraphPin* TypedRowPin = CreatePin(GetTypedRowPinDirection(), UEdGraphSchema_K2::PC_Wildcard, GetTypedRowPinName());
	TypedRowPin->PinFriendlyName = GetTypedRowPinFriendlyName();
	SetPinToolTip(*TypedRowPin, GetTypedRowPinDescription());

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLTypedRowK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("ResultFriendlyName", "Result");
	SetPinToolTip(*ResultPin, LOCTEXT("ResultTooltip", "Raw SQL query result for success state, rows, and error details."));

	Super::AllocateDefaultPins();
	RefreshTypedRowPinType();
}

bool UK2Node_ESQLTypedRowSubsystemBase::CanSplitPin(const UEdGraphPin* Pin) const
{
	return !IsESQLIdStructPin(Pin) && Super::CanSplitPin(Pin);
}

FText UK2Node_ESQLTypedRowSubsystemBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return GetMenuTitleText();
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), GetMenuTitleText());
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("AssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return GetMenuTitleText();
}

void UK2Node_ESQLTypedRowSubsystemBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshTypedRowPinType();
	}

	RefreshCustomPinTypes();
}

FText UK2Node_ESQLTypedRowSubsystemBase::GetTooltipText() const
{
	return GetNodeTooltipText();
}

void UK2Node_ESQLTypedRowSubsystemBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	if (!ResolveRowStructType())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingRowTypeOnExpand", "@@ could not infer a typed row struct. Use a literal Table Asset or connect the row pin to a typed struct.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* WorldContextPin = GetWorldContextPin();
	UK2Node_CallFunction* GetSubsystemNode = SpawnSQLSubsystemGetterNode(CompilerContext, *this, SourceGraph, WorldContextPin);

	UK2Node_CallFunction* SubsystemCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	if (!ESQLRuntimeReflectionUtils::BindSQLSubsystemFunction(*SubsystemCallNode, GetSubsystemFunctionName()))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingSubsystemFunctionOnExpand", "@@ could not resolve the runtime SQL subsystem function.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}
	SubsystemCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *SubsystemCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *SubsystemCallNode->GetThenPin());

	GetSubsystemNode->GetReturnValuePin()->MakeLinkTo(SubsystemCallNode->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	UEdGraphPin* SubsystemTableAssetPin = SubsystemCallNode->FindPinChecked(ESQLTypedRowK2NodePins::TableAsset);
	if (TableAssetPin->LinkedTo.Num() > 0)
	{
		CompilerContext.MovePinLinksToIntermediate(*TableAssetPin, *SubsystemTableAssetPin);
	}
	else
	{
		SubsystemTableAssetPin->DefaultObject = TableAssetPin->DefaultObject;
	}

	ExpandOperationPins(CompilerContext, SourceGraph, SubsystemCallNode);

	UEdGraphPin* TypedRowPin = GetTypedRowPin();
	UEdGraphPin* SubsystemTypedRowPin = SubsystemCallNode->FindPinChecked(GetTypedRowPinName());
	SubsystemTypedRowPin->PinType = TypedRowPin->PinType;
	if (GetTypedRowPinDirection() == EGPD_Output)
	{
		CompilerContext.MovePinLinksToIntermediate(*TypedRowPin, *SubsystemTypedRowPin);
	}
	else
	{
		MoveOrCopyPinToIntermediate(CompilerContext, TypedRowPin, SubsystemTypedRowPin);
	}

	CompilerContext.MovePinLinksToIntermediate(*GetQueryResultPin(), *SubsystemCallNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLTypedRowSubsystemBase::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLTypedRowSubsystemBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshTypedRowPinType();
	RefreshCustomPinTypes();
}

void UK2Node_ESQLTypedRowSubsystemBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLTypedRowSubsystemBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLTypedRowSubsystemBase::GetMenuCategory() const
{
	return LOCTEXT("SQLMenuCategory", "SQL");
}

bool UK2Node_ESQLTypedRowSubsystemBase::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin == GetTypedRowPin() && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		const bool bValidStruct = OtherPin->PinType.ContainerType == EPinContainerType::None
			&& (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard);
		if (!bValidStruct)
		{
			OutReason = TEXT("Row pin must connect to a struct");
			return true;
		}
	}

	return false;
}

void UK2Node_ESQLTypedRowSubsystemBase::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	const UEdGraphPin* TypedRowPin = GetTypedRowPin();
	if (!TableAssetPin || !TypedRowPin)
	{
		MessageLog.Error(*LOCTEXT("MissingPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0)
	{
		const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
		if (!TableAsset)
		{
			MessageLog.Error(*LOCTEXT("NoTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
			return;
		}

		if (!TableAsset->RowStruct)
		{
			MessageLog.Error(*LOCTEXT("MissingRowStructError", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
			return;
		}
	}

	if (!ResolveRowStructType())
	{
		MessageLog.Error(*LOCTEXT("UnresolvedRowStructError", "@@ could not infer the row struct type. Use a literal Table Asset or connect the row pin to a typed struct.").ToString(), this);
		return;
	}

	ValidateOperationPins(MessageLog);
}

void UK2Node_ESQLTypedRowSubsystemBase::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLTypedRowSubsystemBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetTypedRowPin())
	{
		const UEdGraphPin* TableAssetPin = GetTableAssetPin();
		const bool bTypedRowAuthority = TableAssetPin && (TableAssetPin->LinkedTo.Num() > 0 || TableAssetPin->DefaultObject == nullptr);
		if (bTypedRowAuthority)
		{
			RefreshTypedRowPinType();
		}
	}
	else if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshTypedRowPinType();
	}

	RefreshCustomPinTypes();
}

UEdGraphPin* UK2Node_ESQLTypedRowSubsystemBase::GetWorldContextPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLTypedRowK2NodePins::WorldContextObject)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLTypedRowSubsystemBase::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLTypedRowK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLTypedRowSubsystemBase::GetTypedRowPin() const
{
	return FindPinChecked(GetTypedRowPinName());
}

UEdGraphPin* UK2Node_ESQLTypedRowSubsystemBase::GetQueryResultPin() const
{
	return FindPinChecked(ESQLTypedRowK2NodePins::Result);
}

UScriptStruct* UK2Node_ESQLTypedRowSubsystemBase::ResolveRowStructType() const
{
	if (const UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (TableAssetPin->LinkedTo.Num() == 0)
		{
			if (const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
			{
				return const_cast<UScriptStruct*>(TableAsset->RowStruct);
			}
		}
	}

	if (const UEdGraphPin* TypedRowPin = GetTypedRowPin())
	{
		if (TypedRowPin->LinkedTo.Num() > 0)
		{
			for (const UEdGraphPin* LinkedPin : TypedRowPin->LinkedTo)
			{
				if (UScriptStruct* LinkedStruct = ExtractStructTypeFromPin(LinkedPin))
				{
					return LinkedStruct;
				}
			}
		}

		return ExtractStructTypeFromPin(TypedRowPin);
	}

	return nullptr;
}

void UK2Node_ESQLTypedRowSubsystemBase::RefreshTypedRowPinType()
{
	SetTypedRowPinType(ResolveRowStructType());
}

void UK2Node_ESQLTypedRowSubsystemBase::SetTypedRowPinType(UScriptStruct* NewRowStruct)
{
	UEdGraphPin* TypedRowPin = GetTypedRowPin();
	UScriptStruct* OldRowStruct = ExtractStructTypeFromPin(TypedRowPin);
	if (OldRowStruct == NewRowStruct && TypedRowPin->PinType.ContainerType == EPinContainerType::None)
	{
		return;
	}

	if (TypedRowPin->SubPins.Num() > 0)
	{
		GetSchema()->RecombinePin(TypedRowPin);
	}

	TypedRowPin->PinType.ContainerType = EPinContainerType::None;
	TypedRowPin->PinType.PinCategory = NewRowStruct ? UEdGraphSchema_K2::PC_Struct : UEdGraphSchema_K2::PC_Wildcard;
	TypedRowPin->PinType.PinSubCategory = NAME_None;
	TypedRowPin->PinType.PinSubCategoryObject = NewRowStruct;
	CachedNodeTitle.Clear();
}

void UK2Node_ESQLTypedRowSubsystemBase::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

FName UK2Node_ESQLGetRow::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("LoadSQLRow"));
	return FunctionName;
}

FText UK2Node_ESQLGetRow::GetMenuTitleText() const
{
	return LOCTEXT("GetSQLRowMenuTitle", "Get SQL Row");
}

FText UK2Node_ESQLGetRow::GetNodeTooltipText() const
{
	return LOCTEXT("GetSQLRowTooltip", "Loads one typed row from a SQL table asset through the runtime SQL subsystem.");
}

FName UK2Node_ESQLGetRow::GetTypedRowPinName() const
{
	return ESQLTypedRowK2NodePins::OutRow;
}

FText UK2Node_ESQLGetRow::GetTypedRowPinFriendlyName() const
{
	return LOCTEXT("GetSQLRowFriendlyName", "Row");
}

FText UK2Node_ESQLGetRow::GetTypedRowPinDescription() const
{
	return LOCTEXT("GetSQLRowDescription", "Typed row loaded from the SQL table asset.");
}

EEdGraphPinDirection UK2Node_ESQLGetRow::GetTypedRowPinDirection() const
{
	return EGPD_Output;
}

void UK2Node_ESQLGetRow::AllocateOperationPins()
{
	UEdGraphPin* RowIdPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLId::StaticStruct(), ESQLTypedRowK2NodePins::RowId);
	RowIdPin->PinFriendlyName = LOCTEXT("GetSQLRowIdFriendlyName", "SQL Id");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(RowIdPin);
	SetPinToolTip(*RowIdPin, LOCTEXT("GetSQLRowIdTooltip", "SQL identifier that provides the row id value for the typed row lookup."));
}

void UK2Node_ESQLGetRow::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLTypedRowK2NodePins::RowId), FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::SqlId));
}

void UK2Node_ESQLGetRow::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	const UEdGraphPin* RowIdPin = FindPinChecked(ESQLTypedRowK2NodePins::RowId);
	FESQLId SqlId;
	if (RowIdPin->LinkedTo.Num() == 0 && !TryGetSqlIdFromStructDefault(RowIdPin, SqlId))
	{
		MessageLog.Error(*LOCTEXT("MissingRowIdError", "@@ requires an SQL Id when the pin is not linked.").ToString(), this);
	}
}

FName UK2Node_ESQLResolveSQLIdRow::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("LoadSQLRow"));
	return FunctionName;
}

FText UK2Node_ESQLResolveSQLIdRow::GetMenuTitleText() const
{
	return LOCTEXT("ResolveSQLIdRowMenuTitle", "Resolve SQL Id Row");
}

FText UK2Node_ESQLResolveSQLIdRow::GetNodeTooltipText() const
{
	return LOCTEXT("ResolveSQLIdRowTooltip", "Loads one typed row from a SQL Id through the runtime SQL subsystem. This is the generic typed fallback when UI flows already carry FESQLId values.");
}

FName UK2Node_ESQLResolveSQLIdRow::GetTypedRowPinName() const
{
	return ESQLTypedRowK2NodePins::OutRow;
}

FText UK2Node_ESQLResolveSQLIdRow::GetTypedRowPinFriendlyName() const
{
	return LOCTEXT("ResolveSQLIdRowFriendlyName", "Row");
}

FText UK2Node_ESQLResolveSQLIdRow::GetTypedRowPinDescription() const
{
	return LOCTEXT("ResolveSQLIdRowDescription", "Typed row loaded from the SQL Id value.");
}

EEdGraphPinDirection UK2Node_ESQLResolveSQLIdRow::GetTypedRowPinDirection() const
{
	return EGPD_Output;
}

void UK2Node_ESQLResolveSQLIdRow::AllocateOperationPins()
{
	UEdGraphPin* SqlIdPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLId::StaticStruct(), ESQLTypedRowK2NodePins::SqlId);
	SqlIdPin->PinFriendlyName = LOCTEXT("ResolveSQLIdFriendlyName", "SQL Id");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(SqlIdPin);
	SetPinToolTip(*SqlIdPin, LOCTEXT("ResolveSQLIdTooltip", "SQL identifier that provides the row id value for the typed row lookup."));
}

void UK2Node_ESQLResolveSQLIdRow::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLTypedRowK2NodePins::SqlId), FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::SqlId));
}

FName UK2Node_ESQLSaveRow::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("SaveSQLRow"));
	return FunctionName;
}

FText UK2Node_ESQLSaveRow::GetMenuTitleText() const
{
	return LOCTEXT("SaveSQLRowMenuTitle", "Save SQL Row");
}

FText UK2Node_ESQLSaveRow::GetNodeTooltipText() const
{
	return LOCTEXT("SaveSQLRowTooltip", "Saves one typed row through a SQL table asset and resolves the final row id through the runtime SQL subsystem.");
}

FName UK2Node_ESQLSaveRow::GetTypedRowPinName() const
{
	return ESQLTypedRowK2NodePins::RowData;
}

FText UK2Node_ESQLSaveRow::GetTypedRowPinFriendlyName() const
{
	return LOCTEXT("SaveSQLRowFriendlyName", "Row");
}

FText UK2Node_ESQLSaveRow::GetTypedRowPinDescription() const
{
	return LOCTEXT("SaveSQLRowDescription", "Typed row data to save into the SQL table asset.");
}

EEdGraphPinDirection UK2Node_ESQLSaveRow::GetTypedRowPinDirection() const
{
	return EGPD_Input;
}

void UK2Node_ESQLSaveRow::AllocateOperationPins()
{
	UEdGraphPin* RowIdOverridePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, ESQLTypedRowK2NodePins::RowIdOverride);
	RowIdOverridePin->PinFriendlyName = LOCTEXT("SaveSQLRowIdOverrideFriendlyName", "Row Id Override");

	UEdGraphPin* ResolvedRowIdPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_String, ESQLTypedRowK2NodePins::OutResolvedRowId);
	ResolvedRowIdPin->PinFriendlyName = LOCTEXT("ResolvedRowIdFriendlyName", "Resolved Row Id");
	SetPinToolTip(*ResolvedRowIdPin, LOCTEXT("ResolvedRowIdTooltip", "Final row id returned by the runtime SQL subsystem after the save operation."));
}

void UK2Node_ESQLSaveRow::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLTypedRowK2NodePins::RowIdOverride), FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::RowIdOverride));
	CompilerContext.MovePinLinksToIntermediate(*GetResolvedRowIdPin(), *FunctionNode->FindPinChecked(ESQLTypedRowK2NodePins::OutResolvedRowId));
}

UEdGraphPin* UK2Node_ESQLSaveRow::GetResolvedRowIdPin() const
{
	return FindPinChecked(ESQLTypedRowK2NodePins::OutResolvedRowId);
}

FName UK2Node_ESQLFindFirstRowByField::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("FindFirstSQLRowByField"));
	return FunctionName;
}

FText UK2Node_ESQLFindFirstRowByField::GetMenuTitleText() const
{
	return LOCTEXT("FindFirstSQLRowByFieldMenuTitle", "Find First SQL Row By Field");
}

FText UK2Node_ESQLFindFirstRowByField::GetNodeTooltipText() const
{
	return LOCTEXT("FindFirstSQLRowByFieldTooltip", "Finds the first typed row from a SQL table asset using one field comparison through the runtime SQL subsystem.");
}

FName UK2Node_ESQLFindFirstRowByField::GetTypedRowPinName() const
{
	return ESQLTypedRowK2NodePins::OutRow;
}

FText UK2Node_ESQLFindFirstRowByField::GetTypedRowPinFriendlyName() const
{
	return LOCTEXT("FindFirstSQLRowByFieldFriendlyName", "Row");
}

FText UK2Node_ESQLFindFirstRowByField::GetTypedRowPinDescription() const
{
	return LOCTEXT("FindFirstSQLRowByFieldDescription", "First typed row that matched the SQL field comparison.");
}

EEdGraphPinDirection UK2Node_ESQLFindFirstRowByField::GetTypedRowPinDirection() const
{
	return EGPD_Output;
}

void UK2Node_ESQLFindFirstRowByField::AllocateOperationPins()
{
	UEdGraphPin* FieldNamePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ESQLTypedRowK2NodePins::FieldName);
	FieldNamePin->PinFriendlyName = LOCTEXT("FindFirstFieldNameFriendlyName", "Field Name");
	SetPinToolTip(*FieldNamePin, LOCTEXT("FindFirstFieldNameTooltip", "Field on the SQL row struct used for the filter comparison."));

	UEdGraphPin* OperationPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EESQLFilterOperation>(), ESQLTypedRowK2NodePins::Operation);
	OperationPin->PinFriendlyName = LOCTEXT("FindFirstOperationFriendlyName", "Operation");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(OperationPin);
	SetPinToolTip(*OperationPin, LOCTEXT("FindFirstOperationTooltip", "Comparison applied to the selected SQL field."));

	UEdGraphPin* ValuePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLBindingValue::StaticStruct(), ESQLTypedRowK2NodePins::Value);
	ValuePin->PinFriendlyName = LOCTEXT("FindFirstValueFriendlyName", "Value");
	SetPinToolTip(*ValuePin, LOCTEXT("FindFirstValueTooltip", "Comparison value. With a literal table asset and field selected, this pin retargets to that field type."));
}

void UK2Node_ESQLFindFirstRowByField::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveFieldFilterPinsToIntermediate(CompilerContext, SourceGraph, this, FunctionNode);
}

void UK2Node_ESQLFindFirstRowByField::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	const UEdGraphPin* FieldNamePin = FindPinChecked(ESQLTypedRowK2NodePins::FieldName);
	if (FieldNamePin->LinkedTo.Num() == 0 && FieldNamePin->GetDefaultAsString().IsEmpty())
	{
		MessageLog.Error(*LOCTEXT("MissingFindFirstFieldNameError", "@@ requires a Field Name when the pin is not linked.").ToString(), this);
	}
}

void UK2Node_ESQLFindFirstRowByField::RefreshCustomPinTypes()
{
	RefreshFieldValuePinType(this);
}

#undef LOCTEXT_NAMESPACE
