// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "K2Node/ESQLRowQueryK2Nodes.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node/ESQLK2FieldFilterUtils.h"
#include "K2Node/ESQLRuntimeReflectionUtils.h"
#include "K2Node_CallFunction.h"
#include "K2Node_Self.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Styling/AppStyle.h"
#include "TableAsset/ESQLTableAsset.h"

#define LOCTEXT_NAMESPACE "ESQLRowQueryK2Nodes"

namespace ESQLRowQueryK2NodePins
{
	const FName WorldContextObject(TEXT("WorldContextObject"));
	const FName TableAsset(TEXT("TableAsset"));
	const FName QuerySpec(TEXT("QuerySpec"));
	const FName OutCount(TEXT("OutCount"));
	const FName OutRows(TEXT("OutRows"));
	const FName Result(TEXT("Result"));
	const FName MaxRows(TEXT("MaxRows"));
	const FName FieldName(TEXT("FieldName"));
	const FName Operation(TEXT("Operation"));
	const FName Value(TEXT("Value"));
	const FName PageIndex(TEXT("PageIndex"));
	const FName PageSize(TEXT("PageSize"));
}

namespace
{
	bool ShouldRegisterBlueprintAction(const UClass* NodeClass)
	{
		return NodeClass && !NodeClass->HasMetaData(TEXT("ESQLHideFromBlueprintPalette"));
	}

	UScriptStruct* ExtractStructTypeFromArrayPin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.ContainerType != EPinContainerType::Array)
		{
			return nullptr;
		}

		if (Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
		{
			return nullptr;
		}

		return Cast<UScriptStruct>(Pin->PinType.PinSubCategoryObject.Get());
	}

	void MoveOrCopyPinToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	}

	UK2Node_CallFunction* SpawnSQLSubsystemGetterNode(FKismetCompilerContext& CompilerContext, UK2Node& SourceNode, UEdGraph* SourceGraph, UEdGraphPin* WorldContextPin)
	{
		static const FName ContextObjectPinName(TEXT("ContextObject"));
		static const FName ClassPinName(TEXT("Class"));

		UK2Node_CallFunction* GetSubsystemNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(&SourceNode, SourceGraph);
		ESQLRuntimeReflectionUtils::BindGameInstanceSubsystemGetter(*GetSubsystemNode);
		GetSubsystemNode->AllocateDefaultPins();

		UEdGraphPin* GetterWorldContextPin = GetSubsystemNode->FindPinChecked(ContextObjectPinName);
		if (WorldContextPin && WorldContextPin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*WorldContextPin, *GetterWorldContextPin);
		}
		else if (WorldContextPin && WorldContextPin->DefaultObject)
		{
			GetterWorldContextPin->DefaultObject = WorldContextPin->DefaultObject;
		}
		else
		{
			UK2Node_Self* SelfNode = CompilerContext.SpawnIntermediateNode<UK2Node_Self>(&SourceNode, SourceGraph);
			SelfNode->AllocateDefaultPins();
			SelfNode->FindPinChecked(UEdGraphSchema_K2::PN_Self)->MakeLinkTo(GetterWorldContextPin);
		}

		UEdGraphPin* GetterClassPin = GetSubsystemNode->FindPinChecked(ClassPinName);
		GetterClassPin->DefaultObject = UESQLSubsystem::StaticClass();

		UEdGraphPin* GetterResultPin = GetSubsystemNode->GetReturnValuePin();
		GetterResultPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Object;
		GetterResultPin->PinType.PinSubCategory = NAME_None;
		GetterResultPin->PinType.PinSubCategoryObject = UESQLSubsystem::StaticClass();
		return GetSubsystemNode;
	}

	bool HasExplicitValue(const UEdGraphPin* Pin)
	{
		if (!Pin)
		{
			return false;
		}

		if (Pin->LinkedTo.Num() > 0)
		{
			return true;
		}

		return !Pin->DefaultValue.IsEmpty() && Pin->DefaultValue != Pin->AutogeneratedDefaultValue;
	}

	void MoveFieldFilterPinsToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node* SourceNode, UK2Node_CallFunction* FunctionNode)
	{
		MoveOrCopyPinToIntermediate(CompilerContext, SourceNode->FindPinChecked(ESQLRowQueryK2NodePins::FieldName), FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::FieldName));
		MoveOrCopyPinToIntermediate(CompilerContext, SourceNode->FindPinChecked(ESQLRowQueryK2NodePins::Operation), FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::Operation));
		ESQLK2FieldFilterUtils::MoveValuePinToBindingPin(CompilerContext, SourceGraph, SourceNode, SourceNode->FindPinChecked(ESQLRowQueryK2NodePins::Value), FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::Value));
	}

	void RefreshFieldValuePinType(UK2Node* Node)
	{
		if (UEdGraphPin* ValuePin = Node ? Node->FindPin(ESQLRowQueryK2NodePins::Value) : nullptr)
		{
			ESQLK2FieldFilterUtils::ApplyFieldValuePinType(*ValuePin, ESQLK2FieldFilterUtils::ResolveLiteralFieldProperty(Node, ESQLRowQueryK2NodePins::TableAsset, ESQLRowQueryK2NodePins::FieldName));
		}
	}
}

void UK2Node_ESQLRowArraySubsystemBase::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* WorldContextPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), ESQLRowQueryK2NodePins::WorldContextObject);
	WorldContextPin->PinFriendlyName = LOCTEXT("WorldContextFriendlyName", "World Context");
	SetPinToolTip(*WorldContextPin, LOCTEXT("WorldContextTooltip", "Runtime world context used to initialize and query the SQL table asset."));

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLRowQueryK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("TableAssetFriendlyName", "Table Asset");
	SetPinToolTip(*TableAssetPin, LOCTEXT("TableAssetTooltip", "The SQL table asset that owns the row struct and query behavior."));

	AllocateOperationPins();

	UEdGraphNode::FCreatePinParams RowsPinParams;
	RowsPinParams.ContainerType = EPinContainerType::Array;
	UEdGraphPin* RowsPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Wildcard, ESQLRowQueryK2NodePins::OutRows, RowsPinParams);
	RowsPin->PinFriendlyName = LOCTEXT("RowsFriendlyName", "Rows");
	SetPinToolTip(*RowsPin, LOCTEXT("RowsTooltip", "Typed rows loaded from the SQL table asset."));

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLRowQueryK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("ResultFriendlyName", "Result");
	SetPinToolTip(*ResultPin, LOCTEXT("ResultTooltip", "Raw SQL query result for success state, rows, and error details."));

	Super::AllocateDefaultPins();
	RefreshRowsPinType();
}

FText UK2Node_ESQLRowArraySubsystemBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return GetMenuTitleText();
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), GetMenuTitleText());
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("AssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return GetMenuTitleText();
}

void UK2Node_ESQLRowArraySubsystemBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshRowsPinType();
	}

	RefreshCustomPinTypes();
}

FText UK2Node_ESQLRowArraySubsystemBase::GetTooltipText() const
{
	return GetNodeTooltipText();
}

void UK2Node_ESQLRowArraySubsystemBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	if (!ResolveRowStructType())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingRowTypeOnExpand", "@@ could not infer a typed row array output. Use a literal Table Asset or connect Rows to a typed struct array.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* WorldContextPin = GetWorldContextPin();
	UK2Node_CallFunction* GetSubsystemNode = SpawnSQLSubsystemGetterNode(CompilerContext, *this, SourceGraph, WorldContextPin);

	UK2Node_CallFunction* SubsystemCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	if (!ESQLRuntimeReflectionUtils::BindSQLSubsystemFunction(*SubsystemCallNode, GetSubsystemFunctionName()))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingRowArraySubsystemFunctionOnExpand", "@@ could not resolve the runtime SQL subsystem function.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}
	SubsystemCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*UEdGraphNode::FindPinChecked(UEdGraphSchema_K2::PN_Execute), *SubsystemCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*UEdGraphNode::FindPinChecked(UEdGraphSchema_K2::PN_Then), *SubsystemCallNode->GetThenPin());

	GetSubsystemNode->GetReturnValuePin()->MakeLinkTo(SubsystemCallNode->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	UEdGraphPin* SubsystemTableAssetPin = SubsystemCallNode->FindPinChecked(ESQLRowQueryK2NodePins::TableAsset);
	if (TableAssetPin->LinkedTo.Num() > 0)
	{
		CompilerContext.MovePinLinksToIntermediate(*TableAssetPin, *SubsystemTableAssetPin);
	}
	else
	{
		SubsystemTableAssetPin->DefaultObject = TableAssetPin->DefaultObject;
	}

	ExpandOperationPins(CompilerContext, SourceGraph, SubsystemCallNode);

	UEdGraphPin* RowsPin = GetRowsPin();
	UEdGraphPin* SubsystemRowsPin = SubsystemCallNode->FindPinChecked(ESQLRowQueryK2NodePins::OutRows);
	SubsystemRowsPin->PinType = RowsPin->PinType;
	CompilerContext.MovePinLinksToIntermediate(*RowsPin, *SubsystemRowsPin);
	CompilerContext.MovePinLinksToIntermediate(*GetQueryResultPin(), *SubsystemCallNode->GetReturnValuePin());

	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLRowArraySubsystemBase::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLRowArraySubsystemBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshRowsPinType();
	RefreshCustomPinTypes();
}

void UK2Node_ESQLRowArraySubsystemBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLRowArraySubsystemBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLRowArraySubsystemBase::GetMenuCategory() const
{
	return LOCTEXT("SQLMenuCategory", "SQL");
}

bool UK2Node_ESQLRowArraySubsystemBase::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin == GetRowsPin() && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		const bool bValidStructArray = OtherPin->PinType.ContainerType == EPinContainerType::Array
			&& (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard);
		if (!bValidStructArray)
		{
			OutReason = TEXT("Rows must connect to an array of structs");
			return true;
		}
	}

	return false;
}

void UK2Node_ESQLRowArraySubsystemBase::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	const UEdGraphPin* RowsPin = GetRowsPin();
	if (!TableAssetPin || !RowsPin)
	{
		MessageLog.Error(*LOCTEXT("MissingPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0)
	{
		const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
		if (!TableAsset)
		{
			MessageLog.Error(*LOCTEXT("NoTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
			return;
		}

		if (!TableAsset->RowStruct)
		{
			MessageLog.Error(*LOCTEXT("MissingRowStructError", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
			return;
		}
	}

	if (!ResolveRowStructType())
	{
		MessageLog.Error(*LOCTEXT("UnresolvedRowStructError", "@@ could not infer the output row type. Use a literal Table Asset or connect Rows to a typed struct array.").ToString(), this);
		return;
	}

	ValidateOperationPins(MessageLog);
}

void UK2Node_ESQLRowArraySubsystemBase::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLRowArraySubsystemBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetRowsPin())
	{
		const UEdGraphPin* TableAssetPin = GetTableAssetPin();
		const bool bRowsAuthority = TableAssetPin && (TableAssetPin->LinkedTo.Num() > 0 || TableAssetPin->DefaultObject == nullptr);
		if (bRowsAuthority)
		{
			RefreshRowsPinType();
		}
	}
	else if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshRowsPinType();
	}

	RefreshCustomPinTypes();
}

UEdGraphPin* UK2Node_ESQLRowArraySubsystemBase::GetWorldContextPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLRowQueryK2NodePins::WorldContextObject)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLRowArraySubsystemBase::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLRowQueryK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLRowArraySubsystemBase::GetRowsPin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::OutRows);
}

UEdGraphPin* UK2Node_ESQLRowArraySubsystemBase::GetQueryResultPin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::Result);
}

UScriptStruct* UK2Node_ESQLRowArraySubsystemBase::ResolveRowStructType() const
{
	if (const UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (TableAssetPin->LinkedTo.Num() == 0)
		{
			if (const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
			{
				return const_cast<UScriptStruct*>(TableAsset->RowStruct);
			}
		}
	}

	if (const UEdGraphPin* RowsPin = GetRowsPin())
	{
		if (RowsPin->LinkedTo.Num() > 0)
		{
			for (const UEdGraphPin* LinkedPin : RowsPin->LinkedTo)
			{
				if (UScriptStruct* LinkedStruct = ExtractStructTypeFromArrayPin(LinkedPin))
				{
					return LinkedStruct;
				}
			}
		}

		return ExtractStructTypeFromArrayPin(RowsPin);
	}

	return nullptr;
}

void UK2Node_ESQLRowArraySubsystemBase::RefreshRowsPinType()
{
	SetRowsPinType(ResolveRowStructType());
}

void UK2Node_ESQLRowArraySubsystemBase::SetRowsPinType(UScriptStruct* NewRowStruct)
{
	UEdGraphPin* RowsPin = GetRowsPin();
	UScriptStruct* OldRowStruct = ExtractStructTypeFromArrayPin(RowsPin);
	if (OldRowStruct == NewRowStruct && RowsPin->PinType.ContainerType == EPinContainerType::Array)
	{
		return;
	}

	RowsPin->PinType.ContainerType = EPinContainerType::Array;
	RowsPin->PinType.PinCategory = NewRowStruct ? UEdGraphSchema_K2::PC_Struct : UEdGraphSchema_K2::PC_Wildcard;
	RowsPin->PinType.PinSubCategory = NAME_None;
	RowsPin->PinType.PinSubCategoryObject = NewRowStruct;
	CachedNodeTitle.Clear();
}

void UK2Node_ESQLRowArraySubsystemBase::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

void UK2Node_ESQLQuerySpecSubsystemBase::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* WorldContextPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), ESQLRowQueryK2NodePins::WorldContextObject);
	WorldContextPin->PinFriendlyName = LOCTEXT("QuerySubsystemWorldContextFriendlyName", "World Context");
	WorldContextPin->PinToolTip = LOCTEXT("QuerySubsystemWorldContextTooltip", "Runtime world context used to initialize and query the SQL table asset.").ToString();

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLRowQueryK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("QuerySubsystemTableAssetFriendlyName", "Table Asset");
	TableAssetPin->PinToolTip = LOCTEXT("QuerySubsystemTableAssetTooltip", "The SQL table asset that owns the query target.").ToString();

	UEdGraphPin* QuerySpecPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLQuerySpec::StaticStruct(), ESQLRowQueryK2NodePins::QuerySpec);
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(QuerySpecPin);
	QuerySpecPin->bHidden = true;

	AllocateQueryClausePins();
	AllocateResultPins();

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLRowQueryK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("QuerySubsystemResultFriendlyName", "Result");
	ResultPin->PinToolTip = LOCTEXT("QuerySubsystemResultTooltip", "Raw SQL query result for success state, rows, and error details.").ToString();

	Super::AllocateDefaultPins();
	RefreshQueryClausePinTypes();
}

FText UK2Node_ESQLQuerySpecSubsystemBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return GetMenuTitleText();
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), GetMenuTitleText());
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("QuerySubsystemAssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return GetMenuTitleText();
}

void UK2Node_ESQLQuerySpecSubsystemBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
	}

	RefreshQueryClausePinTypes();
}

FText UK2Node_ESQLQuerySpecSubsystemBase::GetTooltipText() const
{
	return GetNodeTooltipText();
}

void UK2Node_ESQLQuerySpecSubsystemBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingQuerySubsystemTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* WorldContextPin = GetWorldContextPin();
	UK2Node_CallFunction* GetSubsystemNode = SpawnSQLSubsystemGetterNode(CompilerContext, *this, SourceGraph, WorldContextPin);

	UK2Node_CallFunction* SubsystemCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	if (!ESQLRuntimeReflectionUtils::BindSQLSubsystemFunction(*SubsystemCallNode, GetSubsystemFunctionName()))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingQuerySubsystemFunctionOnExpand", "@@ could not resolve the runtime SQL subsystem function.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}
	SubsystemCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*UEdGraphNode::FindPinChecked(UEdGraphSchema_K2::PN_Execute), *SubsystemCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*UEdGraphNode::FindPinChecked(UEdGraphSchema_K2::PN_Then), *SubsystemCallNode->GetThenPin());

	GetSubsystemNode->GetReturnValuePin()->MakeLinkTo(SubsystemCallNode->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	UEdGraphPin* SubsystemTableAssetPin = SubsystemCallNode->FindPinChecked(ESQLRowQueryK2NodePins::TableAsset);
	if (TableAssetPin->LinkedTo.Num() > 0)
	{
		CompilerContext.MovePinLinksToIntermediate(*TableAssetPin, *SubsystemTableAssetPin);
	}
	else
	{
		SubsystemTableAssetPin->DefaultObject = TableAssetPin->DefaultObject;
	}

	UEdGraphPin* FunctionQuerySpecPin = SubsystemCallNode->FindPinChecked(ESQLRowQueryK2NodePins::QuerySpec);
	if (UEdGraphPin* QuerySpecPin = GetQuerySpecPin(); HasExplicitValue(QuerySpecPin))
	{
		MoveOrCopyPinToIntermediate(CompilerContext, QuerySpecPin, FunctionQuerySpecPin);
	}
	else if (UEdGraphPin* BuiltQuerySpecPin = BuildQuerySpecPin(CompilerContext, SourceGraph))
	{
		BuiltQuerySpecPin->MakeLinkTo(FunctionQuerySpecPin);
	}

	ExpandResultPins(CompilerContext, SourceGraph, SubsystemCallNode);
	CompilerContext.MovePinLinksToIntermediate(*GetResultPin(), *SubsystemCallNode->GetReturnValuePin());

	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLQuerySpecSubsystemBase::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLQuerySpecSubsystemBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLQuerySpecSubsystemBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLQuerySpecSubsystemBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLQuerySpecSubsystemBase::GetMenuCategory() const
{
	return LOCTEXT("QuerySubsystemSQLMenuCategory", "SQL|Query");
}

void UK2Node_ESQLQuerySpecSubsystemBase::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin)
	{
		MessageLog.Error(*LOCTEXT("QuerySubsystemMissingPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr)
	{
		MessageLog.Error(*LOCTEXT("QuerySubsystemNoTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
		return;
	}

	if (!HasExplicitValue(GetQuerySpecPin()))
	{
		ValidateQueryClausePins(MessageLog);
	}

	ValidateAdditionalPins(MessageLog);
}

void UK2Node_ESQLQuerySpecSubsystemBase::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLQuerySpecSubsystemBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
	}

	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLQuerySpecSubsystemBase::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);
	GetQueryClauseContextMenuActions(Menu, Context);
}

void UK2Node_ESQLQuerySpecSubsystemBase::AddInputPin()
{
	AddFilterClause();
}

bool UK2Node_ESQLQuerySpecSubsystemBase::CanAddPin() const
{
	return ClauseUiState.NumFilterClauses < MaxClauseCount;
}

void UK2Node_ESQLQuerySpecSubsystemBase::RemoveInputPin(UEdGraphPin* Pin)
{
	RemoveClauseForPin(Pin);
}

bool UK2Node_ESQLQuerySpecSubsystemBase::CanRemovePin(const UEdGraphPin* Pin) const
{
	return Pin && IsQueryClausePinName(Pin->PinName);
}

UEdGraphPin* UK2Node_ESQLQuerySpecSubsystemBase::GetWorldContextPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLRowQueryK2NodePins::WorldContextObject)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLQuerySpecSubsystemBase::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLRowQueryK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLQuerySpecSubsystemBase::GetResultPin() const
{
	return UEdGraphNode::FindPinChecked(ESQLRowQueryK2NodePins::Result);
}

UEdGraphPin* UK2Node_ESQLQuerySpecSubsystemBase::GetQuerySpecPin() const
{
	return UEdGraphNode::FindPin(ESQLRowQueryK2NodePins::QuerySpec);
}

FName UK2Node_ESQLGetRows::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("LoadSQLRows"));
	return FunctionName;
}

FText UK2Node_ESQLGetRows::GetMenuTitleText() const
{
	return LOCTEXT("GetSQLRowsMenuTitle", "Get SQL Rows");
}

FText UK2Node_ESQLGetRows::GetNodeTooltipText() const
{
	return LOCTEXT("GetSQLRowsTooltip", "Loads typed rows from a SQL table asset through the runtime SQL subsystem.");
}

void UK2Node_ESQLGetRows::AllocateOperationPins()
{
	UEdGraphPin* MaxRowsPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, ESQLRowQueryK2NodePins::MaxRows);
	MaxRowsPin->PinFriendlyName = LOCTEXT("MaxRowsFriendlyName", "Max Rows");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(MaxRowsPin);
}

void UK2Node_ESQLGetRows::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLRowQueryK2NodePins::MaxRows), FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::MaxRows));
}

FName UK2Node_ESQLQueryRows::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("QuerySQLRows"));
	return FunctionName;
}

FText UK2Node_ESQLQueryRows::GetMenuTitleText() const
{
	return LOCTEXT("QuerySQLRowsMenuTitle", "Query SQL Rows");
}

FText UK2Node_ESQLQueryRows::GetNodeTooltipText() const
{
	return LOCTEXT("QuerySQLRowsTooltip", "Executes a structured SQL query and returns the raw query result without typed row hydration.");
}

void UK2Node_ESQLQueryRows::AllocateResultPins()
{
}

void UK2Node_ESQLQueryRows::ExpandResultPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
}

FName UK2Node_ESQLCountRowsQuery::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("CountSQLRows"));
	return FunctionName;
}

FText UK2Node_ESQLCountRowsQuery::GetMenuTitleText() const
{
	return LOCTEXT("CountSQLRowsQueryMenuTitle", "Count SQL Rows");
}

FText UK2Node_ESQLCountRowsQuery::GetNodeTooltipText() const
{
	return LOCTEXT("CountSQLRowsQueryTooltip", "Counts SQL rows using the structured query builder and returns the numeric match count.");
}

void UK2Node_ESQLCountRowsQuery::AllocateResultPins()
{
	UEdGraphPin* CountPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Int64, ESQLRowQueryK2NodePins::OutCount);
	CountPin->PinFriendlyName = LOCTEXT("CountSQLRowsQueryCountFriendlyName", "Count");
	CountPin->PinToolTip = LOCTEXT("CountSQLRowsQueryCountTooltip", "Number of rows that matched the structured SQL query.").ToString();
}

void UK2Node_ESQLCountRowsQuery::ExpandResultPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	CompilerContext.MovePinLinksToIntermediate(*GetCountPin(), *FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::OutCount));
}

UEdGraphPin* UK2Node_ESQLCountRowsQuery::GetCountPin() const
{
	return UEdGraphNode::FindPinChecked(ESQLRowQueryK2NodePins::OutCount);
}

FName UK2Node_ESQLFindRows::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("FindSQLRows"));
	return FunctionName;
}

FText UK2Node_ESQLFindRows::GetMenuTitleText() const
{
	return LOCTEXT("FindSQLRowsMenuTitle", "Find SQL Rows");
}

FText UK2Node_ESQLFindRows::GetNodeTooltipText() const
{
	return LOCTEXT("FindSQLRowsTooltip", "Finds typed rows from a SQL table asset using reusable filter clauses, sort rules, limit, and offset settings.");
}

void UK2Node_ESQLFindRows::AllocateOperationPins()
{
	UEdGraphPin* QuerySpecPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLQuerySpec::StaticStruct(), ESQLRowQueryK2NodePins::QuerySpec);
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(QuerySpecPin);
	QuerySpecPin->bHidden = true;
	AllocateQueryClausePins();
}

void UK2Node_ESQLFindRows::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	UEdGraphPin* FunctionQuerySpecPin = FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::QuerySpec);
	if (UEdGraphPin* QuerySpecPin = GetQuerySpecPin(); HasExplicitValue(QuerySpecPin))
	{
		MoveOrCopyPinToIntermediate(CompilerContext, QuerySpecPin, FunctionQuerySpecPin);
		return;
	}

	if (UEdGraphPin* BuiltQuerySpecPin = BuildQuerySpecPin(CompilerContext, SourceGraph))
	{
		BuiltQuerySpecPin->MakeLinkTo(FunctionQuerySpecPin);
	}
}

void UK2Node_ESQLFindRows::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	if (HasExplicitValue(GetQuerySpecPin()))
	{
		return;
	}

	ValidateQueryClausePins(MessageLog);
}

void UK2Node_ESQLFindRows::RefreshCustomPinTypes()
{
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLFindRows::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);
	GetQueryClauseContextMenuActions(Menu, Context);
}

void UK2Node_ESQLFindRows::AddInputPin()
{
	AddFilterClause();
}

bool UK2Node_ESQLFindRows::CanAddPin() const
{
	return ClauseUiState.NumFilterClauses < MaxClauseCount;
}

void UK2Node_ESQLFindRows::RemoveInputPin(UEdGraphPin* Pin)
{
	RemoveClauseForPin(Pin);
}

bool UK2Node_ESQLFindRows::CanRemovePin(const UEdGraphPin* Pin) const
{
	return Pin && IsQueryClausePinName(Pin->PinName);
}

UEdGraphPin* UK2Node_ESQLFindRows::GetQuerySpecPin() const
{
	return UEdGraphNode::FindPin(ESQLRowQueryK2NodePins::QuerySpec);
}

FName UK2Node_ESQLFindRowsByField::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("FindSQLRowsByField"));
	return FunctionName;
}

FText UK2Node_ESQLFindRowsByField::GetMenuTitleText() const
{
	return LOCTEXT("FindSQLRowsByFieldMenuTitle", "Find SQL Rows By Field");
}

FText UK2Node_ESQLFindRowsByField::GetNodeTooltipText() const
{
	return LOCTEXT("FindSQLRowsByFieldTooltip", "Finds typed rows from a SQL table asset using one field comparison through the runtime SQL subsystem.");
}

void UK2Node_ESQLFindRowsByField::AllocateOperationPins()
{
	UEdGraphPin* FieldNamePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ESQLRowQueryK2NodePins::FieldName);
	FieldNamePin->PinFriendlyName = LOCTEXT("FieldNameFriendlyName", "Field Name");
	SetPinToolTip(*FieldNamePin, LOCTEXT("FieldNameTooltip", "Field on the SQL row struct used for the filter comparison."));

	UEdGraphPin* OperationPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EESQLFilterOperation>(), ESQLRowQueryK2NodePins::Operation);
	OperationPin->PinFriendlyName = LOCTEXT("OperationFriendlyName", "Operation");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(OperationPin);
	SetPinToolTip(*OperationPin, LOCTEXT("OperationTooltip", "Comparison applied to the selected SQL field."));

	UEdGraphPin* ValuePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLBindingValue::StaticStruct(), ESQLRowQueryK2NodePins::Value);
	ValuePin->PinFriendlyName = LOCTEXT("ValueFriendlyName", "Value");
	SetPinToolTip(*ValuePin, LOCTEXT("ValueTooltip", "Comparison value. With a literal table asset and field selected, this pin retargets to that field type."));
}

void UK2Node_ESQLFindRowsByField::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveFieldFilterPinsToIntermediate(CompilerContext, SourceGraph, this, FunctionNode);
}

void UK2Node_ESQLFindRowsByField::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	const UEdGraphPin* FieldNamePin = FindPinChecked(ESQLRowQueryK2NodePins::FieldName);
	if (FieldNamePin->LinkedTo.Num() == 0 && FieldNamePin->GetDefaultAsString().IsEmpty())
	{
		MessageLog.Error(*LOCTEXT("MissingFieldNameError", "@@ requires a Field Name when the pin is not linked.").ToString(), this);
	}
}

void UK2Node_ESQLFindRowsByField::RefreshCustomPinTypes()
{
	RefreshFieldValuePinType(this);
}

FName UK2Node_ESQLLoadPage::GetSubsystemFunctionName() const
{
	static const FName FunctionName(TEXT("LoadSQLPageByField"));
	return FunctionName;
}

FText UK2Node_ESQLLoadPage::GetMenuTitleText() const
{
	return LOCTEXT("LoadSQLPageMenuTitle", "Load SQL Page");
}

FText UK2Node_ESQLLoadPage::GetNodeTooltipText() const
{
	return LOCTEXT("LoadSQLPageTooltip", "Loads one typed page of rows from a SQL table asset using one field comparison through the runtime SQL subsystem.");
}

void UK2Node_ESQLLoadPage::AllocateOperationPins()
{
	UEdGraphPin* FieldNamePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ESQLRowQueryK2NodePins::FieldName);
	FieldNamePin->PinFriendlyName = LOCTEXT("LoadPageFieldNameFriendlyName", "Field Name");
	SetPinToolTip(*FieldNamePin, LOCTEXT("LoadPageFieldNameTooltip", "Field on the SQL row struct used for the page filter comparison."));

	UEdGraphPin* OperationPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EESQLFilterOperation>(), ESQLRowQueryK2NodePins::Operation);
	OperationPin->PinFriendlyName = LOCTEXT("LoadPageOperationFriendlyName", "Operation");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(OperationPin);
	SetPinToolTip(*OperationPin, LOCTEXT("LoadPageOperationTooltip", "Comparison applied to the selected SQL field before paging."));

	UEdGraphPin* ValuePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLBindingValue::StaticStruct(), ESQLRowQueryK2NodePins::Value);
	ValuePin->PinFriendlyName = LOCTEXT("LoadPageValueFriendlyName", "Value");
	SetPinToolTip(*ValuePin, LOCTEXT("LoadPageValueTooltip", "Comparison value. With a literal table asset and field selected, this pin retargets to that field type."));

	UEdGraphPin* PageIndexPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, ESQLRowQueryK2NodePins::PageIndex);
	PageIndexPin->PinFriendlyName = LOCTEXT("PageIndexFriendlyName", "Page Index");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(PageIndexPin);
	SetPinToolTip(*PageIndexPin, LOCTEXT("PageIndexTooltip", "Zero-based page index applied after the field filter."));

	UEdGraphPin* PageSizePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, ESQLRowQueryK2NodePins::PageSize);
	PageSizePin->PinFriendlyName = LOCTEXT("PageSizeFriendlyName", "Page Size");
	PageSizePin->DefaultValue = TEXT("50");
	SetPinToolTip(*PageSizePin, LOCTEXT("PageSizeTooltip", "Maximum rows returned for the selected page."));
}

void UK2Node_ESQLLoadPage::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveFieldFilterPinsToIntermediate(CompilerContext, SourceGraph, this, FunctionNode);
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLRowQueryK2NodePins::PageIndex), FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::PageIndex));
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLRowQueryK2NodePins::PageSize), FunctionNode->FindPinChecked(ESQLRowQueryK2NodePins::PageSize));
}

void UK2Node_ESQLLoadPage::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	const UEdGraphPin* FieldNamePin = FindPinChecked(ESQLRowQueryK2NodePins::FieldName);
	if (FieldNamePin->LinkedTo.Num() == 0 && FieldNamePin->GetDefaultAsString().IsEmpty())
	{
		MessageLog.Error(*LOCTEXT("MissingLoadPageFieldNameError", "@@ requires a Field Name when the pin is not linked.").ToString(), this);
	}

	const UEdGraphPin* PageSizePin = FindPinChecked(ESQLRowQueryK2NodePins::PageSize);
	if (PageSizePin->LinkedTo.Num() == 0 && FCString::Atoi(*PageSizePin->GetDefaultAsString()) <= 0)
	{
		MessageLog.Error(*LOCTEXT("InvalidPageSizeError", "@@ requires Page Size to be greater than zero when the pin is not linked.").ToString(), this);
	}

	const UEdGraphPin* PageIndexPin = FindPinChecked(ESQLRowQueryK2NodePins::PageIndex);
	if (PageIndexPin->LinkedTo.Num() == 0 && FCString::Atoi(*PageIndexPin->GetDefaultAsString()) < 0)
	{
		MessageLog.Error(*LOCTEXT("InvalidPageIndexError", "@@ requires Page Index to be zero or greater when the pin is not linked.").ToString(), this);
	}
}

void UK2Node_ESQLLoadPage::RefreshCustomPinTypes()
{
	RefreshFieldValuePinType(this);
}

void UK2Node_ESQLCountRows::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* WorldContextPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), ESQLRowQueryK2NodePins::WorldContextObject);
	WorldContextPin->PinFriendlyName = LOCTEXT("CountRowsWorldContextFriendlyName", "World Context");
	SetPinToolTip(*WorldContextPin, LOCTEXT("CountRowsWorldContextTooltip", "Runtime world context used to initialize and query the SQL table asset."));

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLRowQueryK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("CountRowsTableAssetFriendlyName", "Table Asset");
	SetPinToolTip(*TableAssetPin, LOCTEXT("CountRowsTableAssetTooltip", "The SQL table asset that owns the row struct and query behavior."));

	UEdGraphPin* FieldNamePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ESQLRowQueryK2NodePins::FieldName);
	FieldNamePin->PinFriendlyName = LOCTEXT("CountRowsFieldFriendlyName", "Field Name");
	SetPinToolTip(*FieldNamePin, LOCTEXT("CountRowsFieldTooltip", "Field on the SQL row struct used for the count comparison."));

	UEdGraphPin* OperationPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EESQLFilterOperation>(), ESQLRowQueryK2NodePins::Operation);
	OperationPin->PinFriendlyName = LOCTEXT("CountRowsOperationFriendlyName", "Operation");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(OperationPin);
	SetPinToolTip(*OperationPin, LOCTEXT("CountRowsOperationTooltip", "Comparison applied to the selected SQL field before counting."));

	UEdGraphPin* ValuePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLBindingValue::StaticStruct(), ESQLRowQueryK2NodePins::Value);
	ValuePin->PinFriendlyName = LOCTEXT("CountRowsValueFriendlyName", "Value");
	SetPinToolTip(*ValuePin, LOCTEXT("CountRowsValueTooltip", "Comparison value. With a literal table asset and field selected, this pin retargets to that field type."));

	UEdGraphPin* CountPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Int64, ESQLRowQueryK2NodePins::OutCount);
	CountPin->PinFriendlyName = LOCTEXT("CountRowsCountFriendlyName", "Count");
	SetPinToolTip(*CountPin, LOCTEXT("CountRowsCountTooltip", "Number of rows that matched the SQL field filter."));

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLRowQueryK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("CountRowsResultFriendlyName", "Result");
	SetPinToolTip(*ResultPin, LOCTEXT("CountRowsResultTooltip", "Raw SQL query result for success state, rows, and error details."));

	Super::AllocateDefaultPins();
	RefreshValuePinType();
}

FText UK2Node_ESQLCountRows::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const FText MenuTitle = LOCTEXT("CountSQLRowsByFieldMenuTitle", "Count SQL Rows By Field");
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return MenuTitle;
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), MenuTitle);
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("CountRowsAssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return MenuTitle;
}

void UK2Node_ESQLCountRows::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
	}

	RefreshValuePinType();
}

FText UK2Node_ESQLCountRows::GetTooltipText() const
{
	return LOCTEXT("CountSQLRowsByFieldTooltip", "Counts SQL rows using one field comparison through the runtime SQL subsystem.");
}

void UK2Node_ESQLCountRows::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingCountRowsTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* WorldContextPin = GetWorldContextPin();
	UK2Node_CallFunction* GetSubsystemNode = SpawnSQLSubsystemGetterNode(CompilerContext, *this, SourceGraph, WorldContextPin);

	UK2Node_CallFunction* SubsystemCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	static const FName CountRowsByFieldFunctionName(TEXT("CountSQLRowsByField"));
	if (!ESQLRuntimeReflectionUtils::BindSQLSubsystemFunction(*SubsystemCallNode, CountRowsByFieldFunctionName))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingCountRowsSubsystemFunctionOnExpand", "@@ could not resolve the runtime SQL subsystem function.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}
	SubsystemCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *SubsystemCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *SubsystemCallNode->GetThenPin());

	GetSubsystemNode->GetReturnValuePin()->MakeLinkTo(SubsystemCallNode->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	UEdGraphPin* SubsystemTableAssetPin = SubsystemCallNode->FindPinChecked(ESQLRowQueryK2NodePins::TableAsset);
	if (TableAssetPin->LinkedTo.Num() > 0)
	{
		CompilerContext.MovePinLinksToIntermediate(*TableAssetPin, *SubsystemTableAssetPin);
	}
	else
	{
		SubsystemTableAssetPin->DefaultObject = TableAssetPin->DefaultObject;
	}

	MoveFieldFilterPinsToIntermediate(CompilerContext, SourceGraph, this, SubsystemCallNode);
	CompilerContext.MovePinLinksToIntermediate(*GetCountPin(), *SubsystemCallNode->FindPinChecked(ESQLRowQueryK2NodePins::OutCount));
	CompilerContext.MovePinLinksToIntermediate(*GetQueryResultPin(), *SubsystemCallNode->GetReturnValuePin());

	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLCountRows::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLCountRows::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshValuePinType();
}

void UK2Node_ESQLCountRows::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLCountRows::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLCountRows::GetMenuCategory() const
{
	return LOCTEXT("CountRowsSQLMenuCategory", "SQL");
}

void UK2Node_ESQLCountRows::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin)
	{
		MessageLog.Error(*LOCTEXT("CountRowsMissingPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0)
	{
		const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
		if (!TableAsset)
		{
			MessageLog.Error(*LOCTEXT("CountRowsNoTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
			return;
		}

		if (!TableAsset->RowStruct)
		{
			MessageLog.Error(*LOCTEXT("CountRowsMissingRowStructError", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
			return;
		}
	}

	const UEdGraphPin* FieldNamePin = GetFieldNamePin();
	if (FieldNamePin->LinkedTo.Num() == 0 && FieldNamePin->GetDefaultAsString().IsEmpty())
	{
		MessageLog.Error(*LOCTEXT("CountRowsMissingFieldNameError", "@@ requires a Field Name when the pin is not linked.").ToString(), this);
	}
}

void UK2Node_ESQLCountRows::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLCountRows::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
	}

	RefreshValuePinType();
}

UEdGraphPin* UK2Node_ESQLCountRows::GetWorldContextPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLRowQueryK2NodePins::WorldContextObject)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLCountRows::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLRowQueryK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLCountRows::GetFieldNamePin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::FieldName);
}

UEdGraphPin* UK2Node_ESQLCountRows::GetOperationPin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::Operation);
}

UEdGraphPin* UK2Node_ESQLCountRows::GetValuePin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::Value);
}

UEdGraphPin* UK2Node_ESQLCountRows::GetCountPin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::OutCount);
}

UEdGraphPin* UK2Node_ESQLCountRows::GetQueryResultPin() const
{
	return FindPinChecked(ESQLRowQueryK2NodePins::Result);
}

void UK2Node_ESQLCountRows::RefreshValuePinType()
{
	ESQLK2FieldFilterUtils::ApplyFieldValuePinType(*GetValuePin(), ESQLK2FieldFilterUtils::ResolveLiteralFieldProperty(this, ESQLRowQueryK2NodePins::TableAsset, ESQLRowQueryK2NodePins::FieldName));
}

void UK2Node_ESQLCountRows::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

#undef LOCTEXT_NAMESPACE
