// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "K2Node/ESQLAsyncTypedK2Nodes.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_AddDelegate.h"
#include "K2Node_AssignmentStatement.h"
#include "K2Node/ESQLRuntimeReflectionUtils.h"
#include "K2Node_CallFunction.h"
#include "K2Node_CreateDelegate.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_IfThenElse.h"
#include "K2Node_Self.h"
#include "K2Node_TemporaryVariable.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Misc/OutputDeviceNull.h"
#include "Shared/ESQLId.h"
#include "Styling/AppStyle.h"
#include "TableAsset/ESQLTableAsset.h"
#include "UObject/PropertyPortFlags.h"

#define LOCTEXT_NAMESPACE "ESQLAsyncTypedK2Nodes"

namespace ESQLAsyncTypedK2NodePins
{
	const FName TableAsset(TEXT("TableAsset"));
	const FName RowId(TEXT("RowId"));
	const FName QuerySpec(TEXT("QuerySpec"));
	const FName Result(TEXT("Result"));
	const FName OutRow(TEXT("OutRow"));
	const FName OutRows(TEXT("OutRows"));
	const FName RowData(TEXT("RowData"));
	const FName OnSuccess(TEXT("OnSuccess"));
	const FName OnFailure(TEXT("OnFailure"));
}

namespace
{
	bool ShouldRegisterBlueprintAction(const UClass* NodeClass)
	{
		return NodeClass && !NodeClass->HasMetaData(TEXT("ESQLHideFromBlueprintPalette"));
	}

	const UEdGraphPin* FindPinByName(const TArray<UEdGraphPin*>& PinsToSearch, const FName PinName)
	{
		for (const UEdGraphPin* Pin : PinsToSearch)
		{
			if (Pin && Pin->PinName == PinName)
			{
				return Pin;
			}
		}

		return nullptr;
	}

	UScriptStruct* ExtractStructTypeFromPin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.ContainerType != EPinContainerType::None)
		{
			return nullptr;
		}

		if (Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
		{
			return nullptr;
		}

		return Cast<UScriptStruct>(Pin->PinType.PinSubCategoryObject.Get());
	}

	UScriptStruct* ExtractStructTypeFromArrayPin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.ContainerType != EPinContainerType::Array)
		{
			return nullptr;
		}

		if (Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
		{
			return nullptr;
		}

		return Cast<UScriptStruct>(Pin->PinType.PinSubCategoryObject.Get());
	}

	bool IsESQLIdStructPin(const UEdGraphPin* Pin)
	{
		const UScriptStruct* PinStruct = ExtractStructTypeFromPin(Pin);
		const UScriptStruct* SqlIdStruct = FESQLId::StaticStruct();
		return PinStruct
			&& SqlIdStruct
			&& (PinStruct == SqlIdStruct || PinStruct->GetName().Contains(SqlIdStruct->GetName(), ESearchCase::IgnoreCase));
	}

	void CopyPinDefaultValue(UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	}

	void MoveOrCopyPinToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		CopyPinDefaultValue(SourcePin, TargetPin);
	}

	bool HasExplicitValue(const UEdGraphPin* Pin)
	{
		if (!Pin)
		{
			return false;
		}

		if (Pin->LinkedTo.Num() > 0)
		{
			return true;
		}

		return !Pin->DefaultValue.IsEmpty() && Pin->DefaultValue != Pin->AutogeneratedDefaultValue;
	}

	UK2Node_AssignmentStatement* SpawnAssignmentNode(
		UK2Node* CurrentNode,
		UEdGraph* SourceGraph,
		FKismetCompilerContext& CompilerContext,
		UEdGraphPin* ExecPin,
		UEdGraphPin* VariablePin,
		UEdGraphPin* ValuePin)
	{
		const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
		UK2Node_AssignmentStatement* AssignNode = CompilerContext.SpawnIntermediateNode<UK2Node_AssignmentStatement>(CurrentNode, SourceGraph);
		AssignNode->AllocateDefaultPins();
		Schema->TryCreateConnection(ExecPin, AssignNode->GetExecPin());
		Schema->TryCreateConnection(VariablePin, AssignNode->GetVariablePin());
		AssignNode->NotifyPinConnectionListChanged(AssignNode->GetVariablePin());
		Schema->TryCreateConnection(AssignNode->GetValuePin(), ValuePin);
		AssignNode->NotifyPinConnectionListChanged(AssignNode->GetValuePin());
		return AssignNode;
	}
}

UK2Node_ESQLAsyncTypedResultBase::UK2Node_ESQLAsyncTypedResultBase(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	ProxyActivateFunctionName = GET_FUNCTION_NAME_CHECKED(UBlueprintAsyncActionBase, Activate);
	AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
}

void UK2Node_ESQLAsyncTypedResultBase::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	UEdGraphNode::FCreatePinParams TypedPinParams;
	TypedPinParams.ContainerType = GetTypedDataPinContainerType();
	UEdGraphPin* TypedPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Wildcard, GetTypedDataPinName(), TypedPinParams);
	TypedPin->PinFriendlyName = GetTypedDataPinFriendlyName();
	SetPinToolTip(*TypedPin, GetTypedDataPinDescription());
	RefreshTypedDataPinType();
}

bool UK2Node_ESQLAsyncTypedResultBase::CanSplitPin(const UEdGraphPin* Pin) const
{
	return !IsESQLIdStructPin(Pin) && Super::CanSplitPin(Pin);
}

FText UK2Node_ESQLAsyncTypedResultBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return GetMenuTitleText();
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), GetMenuTitleText());
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("AsyncAssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return GetMenuTitleText();
}

FText UK2Node_ESQLAsyncTypedResultBase::GetTooltipText() const
{
	return GetNodeTooltipText();
}

void UK2Node_ESQLAsyncTypedResultBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshTypedDataPinType();
	}
}

void UK2Node_ESQLAsyncTypedResultBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshTypedDataPinType();
}

void UK2Node_ESQLAsyncTypedResultBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLAsyncTypedResultBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLAsyncTypedResultBase::GetMenuCategory() const
{
	return LOCTEXT("SQLAsyncMenuCategory", "SQL");
}

bool UK2Node_ESQLAsyncTypedResultBase::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin == GetTypedDataPin() && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		const bool bValidPin = GetTypedDataPinContainerType() == EPinContainerType::Array
			? (OtherPin->PinType.ContainerType == EPinContainerType::Array && (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard))
			: (OtherPin->PinType.ContainerType == EPinContainerType::None && (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard));

		if (!bValidPin)
		{
			OutReason = GetTypedDataPinContainerType() == EPinContainerType::Array
				? TEXT("Rows must connect to an array of structs")
				: TEXT("Row must connect to a struct");
			return true;
		}
	}

	return Super::IsConnectionDisallowed(MyPin, OtherPin, OutReason);
}

void UK2Node_ESQLAsyncTypedResultBase::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLAsyncTypedResultBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetTypedDataPin())
	{
		RefreshTypedDataPinType();
	}
	else if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshTypedDataPinType();
	}
}

void UK2Node_ESQLAsyncTypedResultBase::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || TableAssetPin->LinkedTo.Num() > 0)
	{
		MessageLog.Error(*LOCTEXT("AsyncTypedLiteralTableRequired", "@@ currently requires a literal SQL Table Asset so the typed async result can be hydrated deterministically.").ToString(), this);
		return;
	}

	const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
	if (!TableAsset)
	{
		MessageLog.Error(*LOCTEXT("AsyncTypedMissingTable", "No SQL Table Asset specified in @@").ToString(), this);
		return;
	}

	if (!TableAsset->RowStruct)
	{
		MessageLog.Error(*LOCTEXT("AsyncTypedMissingRowStruct", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
		return;
	}

	if (!ResolveRowStructType())
	{
		MessageLog.Error(*LOCTEXT("AsyncTypedMissingOutputType", "@@ could not infer the typed async output. Use a literal SQL Table Asset or connect the typed output pin to a struct-compatible type.").ToString(), this);
		return;
	}
}

UEdGraphPin* UK2Node_ESQLAsyncTypedResultBase::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLAsyncTypedK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLAsyncTypedResultBase::GetTypedDataPin() const
{
	return FindPinChecked(GetTypedDataPinName());
}

UEdGraphPin* UK2Node_ESQLAsyncTypedResultBase::GetResultPin() const
{
	return FindPinChecked(ESQLAsyncTypedK2NodePins::Result);
}

UScriptStruct* UK2Node_ESQLAsyncTypedResultBase::ResolveRowStructType() const
{
	if (const UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			return const_cast<UScriptStruct*>(TableAsset->RowStruct);
		}
	}

	const UEdGraphPin* TypedPin = GetTypedDataPin();
	if (!TypedPin)
	{
		return nullptr;
	}

	if (TypedPin->LinkedTo.Num() > 0)
	{
		for (const UEdGraphPin* LinkedPin : TypedPin->LinkedTo)
		{
			UScriptStruct* LinkedStruct = GetTypedDataPinContainerType() == EPinContainerType::Array
				? ExtractStructTypeFromArrayPin(LinkedPin)
				: ExtractStructTypeFromPin(LinkedPin);
			if (LinkedStruct)
			{
				return LinkedStruct;
			}
		}
	}

	return GetTypedDataPinContainerType() == EPinContainerType::Array
		? ExtractStructTypeFromArrayPin(TypedPin)
		: ExtractStructTypeFromPin(TypedPin);
}

void UK2Node_ESQLAsyncTypedResultBase::RefreshTypedDataPinType()
{
	SetTypedDataPinType(ResolveRowStructType());
}

void UK2Node_ESQLAsyncTypedResultBase::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

void UK2Node_ESQLAsyncTypedResultBase::SetTypedDataPinType(UScriptStruct* NewRowStruct)
{
	UEdGraphPin* TypedPin = GetTypedDataPin();
	const UScriptStruct* OldStruct = GetTypedDataPinContainerType() == EPinContainerType::Array
		? ExtractStructTypeFromArrayPin(TypedPin)
		: ExtractStructTypeFromPin(TypedPin);
	if (OldStruct == NewRowStruct && TypedPin->PinType.ContainerType == GetTypedDataPinContainerType())
	{
		return;
	}

	TypedPin->PinType.ContainerType = GetTypedDataPinContainerType();
	TypedPin->PinType.PinCategory = NewRowStruct ? UEdGraphSchema_K2::PC_Struct : UEdGraphSchema_K2::PC_Wildcard;
	TypedPin->PinType.PinSubCategory = NAME_None;
	TypedPin->PinType.PinSubCategoryObject = NewRowStruct;
	CachedNodeTitle.Clear();
}

bool UK2Node_ESQLAsyncTypedResultBase::HandleDelegates(const TArray<FBaseAsyncTaskHelper::FOutputPinAndLocalVariable>& VariableOutputs, UEdGraphPin* ProxyObjectPin, UEdGraphPin*& InOutLastThenPin, UEdGraph* SourceGraph, FKismetCompilerContext& CompilerContext)
{
	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	check(Schema);

	if (!ProxyFactoryClass || !ProxyClass)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncTypedMissingProxyClass", "@@ could not resolve the internal SQL async action class.").ToString(), this);
		return false;
	}

	const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(GetTableAssetPin()->DefaultObject);
	if (!TableAsset)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncTypedHandleDelegateMissingTable", "@@ requires a literal SQL Table Asset for async typed result hydration.").ToString(), this);
		return false;
	}

	auto FindOutputPairByName = [&VariableOutputs](const FName PinName) -> const FBaseAsyncTaskHelper::FOutputPinAndLocalVariable*
	{
		for (const FBaseAsyncTaskHelper::FOutputPinAndLocalVariable& OutputPair : VariableOutputs)
		{
			if (OutputPair.OutputPin && OutputPair.OutputPin->PinName == PinName)
			{
				return &OutputPair;
			}
		}

		return nullptr;
	};

	const FBaseAsyncTaskHelper::FOutputPinAndLocalVariable* ResultPair = FindOutputPairByName(ESQLAsyncTypedK2NodePins::Result);
	const FBaseAsyncTaskHelper::FOutputPinAndLocalVariable* TypedPair = FindOutputPairByName(GetTypedDataPinName());
	if (!TypedPair)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncTypedHandleDelegateMissingTypedPair", "@@ failed to create a temporary typed async output variable.").ToString(), this);
		return false;
	}

	bool bIsErrorFree = true;
	for (TFieldIterator<FMulticastDelegateProperty> PropertyIt(ProxyClass); PropertyIt && bIsErrorFree; ++PropertyIt)
	{
		FMulticastDelegateProperty* CurrentProperty = *PropertyIt;
		UEdGraphPin* ExecPinForDelegate = FindPin(CurrentProperty->GetFName());
		if (!ExecPinForDelegate || ExecPinForDelegate->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec)
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("AsyncTypedMissingDelegateExecPin", "BaseAsyncTask: Cannot find execution pin for delegate @@").ToString(), this);
			return false;
		}

		UK2Node_CustomEvent* CurrentCENode = CompilerContext.SpawnIntermediateNode<UK2Node_CustomEvent>(this, SourceGraph);
		UK2Node_AddDelegate* AddDelegateNode = CompilerContext.SpawnIntermediateNode<UK2Node_AddDelegate>(this, SourceGraph);
		AddDelegateNode->SetFromProperty(CurrentProperty, false, CurrentProperty->GetOwnerClass());
		AddDelegateNode->AllocateDefaultPins();
		bIsErrorFree &= Schema->TryCreateConnection(AddDelegateNode->FindPinChecked(UEdGraphSchema_K2::PN_Self), ProxyObjectPin);
		bIsErrorFree &= Schema->TryCreateConnection(InOutLastThenPin, AddDelegateNode->FindPinChecked(UEdGraphSchema_K2::PN_Execute));
		InOutLastThenPin = AddDelegateNode->FindPinChecked(UEdGraphSchema_K2::PN_Then);

		CurrentCENode->CustomFunctionName = *FString::Printf(TEXT("%s_%s"), *CurrentProperty->GetName(), *CompilerContext.GetGuid(this));
		CurrentCENode->AllocateDefaultPins();
		bIsErrorFree &= FBaseAsyncTaskHelper::CreateDelegateForNewFunction(AddDelegateNode->GetDelegatePin(), CurrentCENode->GetFunctionName(), this, SourceGraph, CompilerContext);
		bIsErrorFree &= FBaseAsyncTaskHelper::CopyEventSignature(CurrentCENode, AddDelegateNode->GetDelegateSignature(), Schema);

		UEdGraphPin* CurrentThenPin = CurrentCENode->FindPinChecked(UEdGraphSchema_K2::PN_Then);
		for (const FBaseAsyncTaskHelper::FOutputPinAndLocalVariable& OutputPair : VariableOutputs)
		{
			if (!OutputPair.OutputPin || OutputPair.OutputPin->PinName == GetTypedDataPinName())
			{
				continue;
			}

			if (UEdGraphPin* PinWithData = CurrentCENode->FindPin(OutputPair.OutputPin->PinName))
			{
				CurrentThenPin = SpawnAssignmentNode(this, SourceGraph, CompilerContext, CurrentThenPin, OutputPair.TempVar->GetVariablePin(), PinWithData)->GetThenPin();
			}
		}

		if (CurrentProperty->GetFName() == ESQLAsyncTypedK2NodePins::OnSuccess)
		{
			UEdGraphPin* EventResultPin = CurrentCENode->FindPinChecked(ESQLAsyncTypedK2NodePins::Result);

			UK2Node_CallFunction* HydrationNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
			if (!ESQLRuntimeReflectionUtils::BindSQLBlueprintLibraryFunction(*HydrationNode, GetHydrationFunctionName()))
			{
				CompilerContext.MessageLog.Error(*LOCTEXT("AsyncTypedMissingHydrationLibraryClass", "@@ could not resolve the runtime SQL blueprint helper class.").ToString(), this);
				return false;
			}
			HydrationNode->AllocateDefaultPins();

			UEdGraphPin* HydrationTableAssetPin = HydrationNode->FindPinChecked(ESQLAsyncTypedK2NodePins::TableAsset);
			HydrationTableAssetPin->DefaultObject = const_cast<UESQLTableAsset*>(TableAsset);
			bIsErrorFree &= Schema->TryCreateConnection(EventResultPin, HydrationNode->FindPinChecked(ESQLAsyncTypedK2NodePins::Result));
			UEdGraphPin* HydratedValuePin = HydrationNode->FindPinChecked(GetTypedDataPinName());
			HydratedValuePin->PinType = TypedPair->OutputPin->PinType;
			bIsErrorFree &= Schema->TryCreateConnection(CurrentThenPin, HydrationNode->GetExecPin());

			CurrentThenPin = SpawnAssignmentNode(this, SourceGraph, CompilerContext, HydrationNode->GetThenPin(), TypedPair->TempVar->GetVariablePin(), HydratedValuePin)->GetThenPin();

			UK2Node_CallFunction* IsSuccessNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
			static const FName IsSQLQueryResultSuccessfulFunctionName(TEXT("IsSQLQueryResultSuccessful"));
			if (!ESQLRuntimeReflectionUtils::BindSQLBlueprintLibraryFunction(*IsSuccessNode, IsSQLQueryResultSuccessfulFunctionName))
			{
				CompilerContext.MessageLog.Error(*LOCTEXT("AsyncTypedMissingSuccessLibraryClass", "@@ could not resolve the runtime SQL blueprint helper class.").ToString(), this);
				return false;
			}
			IsSuccessNode->AllocateDefaultPins();
			bIsErrorFree &= Schema->TryCreateConnection(HydrationNode->GetReturnValuePin(), IsSuccessNode->FindPinChecked(TEXT("QueryResult")));

			UK2Node_IfThenElse* BranchNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
			BranchNode->AllocateDefaultPins();
			bIsErrorFree &= Schema->TryCreateConnection(CurrentThenPin, BranchNode->GetExecPin());
			bIsErrorFree &= Schema->TryCreateConnection(IsSuccessNode->GetReturnValuePin(), BranchNode->GetConditionPin());

			if (ResultPair)
			{
				UK2Node_AssignmentStatement* FailureAssign = SpawnAssignmentNode(this, SourceGraph, CompilerContext, BranchNode->GetElsePin(), ResultPair->TempVar->GetVariablePin(), HydrationNode->GetReturnValuePin());
				bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*FindPinChecked(ESQLAsyncTypedK2NodePins::OnFailure), *FailureAssign->GetThenPin()).CanSafeConnect();
			}
			else
			{
				bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*FindPinChecked(ESQLAsyncTypedK2NodePins::OnFailure), *BranchNode->GetElsePin()).CanSafeConnect();
			}

			bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*ExecPinForDelegate, *BranchNode->GetThenPin()).CanSafeConnect();
		}
		else
		{
			bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*ExecPinForDelegate, *CurrentThenPin).CanSafeConnect();
		}
	}

	return bIsErrorFree;
}

UK2Node_ESQLAsyncGetRow::UK2Node_ESQLAsyncGetRow(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	static const FName AsyncLoadSQLRowFunctionName(TEXT("AsyncLoadSQLRow"));
	ProxyFactoryFunctionName = AsyncLoadSQLRowFunctionName;
	ProxyFactoryClass = ESQLRuntimeReflectionUtils::GetAsyncActionClass(TEXT("ESQLAsyncLoadSQLRow"));
	ProxyClass = ProxyFactoryClass;
}

FText UK2Node_ESQLAsyncGetRow::GetMenuTitleText() const
{
	return LOCTEXT("AsyncGetSQLRowTitle", "Async Load SQL Row");
}

FText UK2Node_ESQLAsyncGetRow::GetNodeTooltipText() const
{
	return LOCTEXT("AsyncGetSQLRowTooltip", "Loads one typed SQL row asynchronously and exposes the hydrated Row output on the node.");
}

FName UK2Node_ESQLAsyncGetRow::GetTypedDataPinName() const
{
	return ESQLAsyncTypedK2NodePins::OutRow;
}

FText UK2Node_ESQLAsyncGetRow::GetTypedDataPinFriendlyName() const
{
	return LOCTEXT("AsyncGetSQLRowOutFriendlyName", "Row");
}

FText UK2Node_ESQLAsyncGetRow::GetTypedDataPinDescription() const
{
	return LOCTEXT("AsyncGetSQLRowOutTooltip", "Typed row hydrated from the async SQL query result.");
}

EPinContainerType UK2Node_ESQLAsyncGetRow::GetTypedDataPinContainerType() const
{
	return EPinContainerType::None;
}

FName UK2Node_ESQLAsyncGetRow::GetHydrationFunctionName() const
{
	static const FName FunctionName(TEXT("PopulateSQLRowFromResult"));
	return FunctionName;
}

UK2Node_ESQLAsyncGetRows::UK2Node_ESQLAsyncGetRows(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	static const FName AsyncLoadSQLRowsFunctionName(TEXT("AsyncLoadSQLRows"));
	ProxyFactoryFunctionName = AsyncLoadSQLRowsFunctionName;
	ProxyFactoryClass = ESQLRuntimeReflectionUtils::GetAsyncActionClass(TEXT("ESQLAsyncLoadSQLRows"));
	ProxyClass = ProxyFactoryClass;
}

FText UK2Node_ESQLAsyncGetRows::GetMenuTitleText() const
{
	return LOCTEXT("AsyncGetSQLRowsTitle", "Async Load SQL Rows");
}

FText UK2Node_ESQLAsyncGetRows::GetNodeTooltipText() const
{
	return LOCTEXT("AsyncGetSQLRowsTooltip", "Loads typed SQL rows asynchronously and routes success or failure through dedicated exec pins.");
}

FName UK2Node_ESQLAsyncGetRows::GetTypedDataPinName() const
{
	return ESQLAsyncTypedK2NodePins::OutRows;
}

FText UK2Node_ESQLAsyncGetRows::GetTypedDataPinFriendlyName() const
{
	return LOCTEXT("AsyncGetSQLRowsOutFriendlyName", "Rows");
}

FText UK2Node_ESQLAsyncGetRows::GetTypedDataPinDescription() const
{
	return LOCTEXT("AsyncGetSQLRowsOutTooltip", "Typed rows hydrated from the async SQL query result.");
}

EPinContainerType UK2Node_ESQLAsyncGetRows::GetTypedDataPinContainerType() const
{
	return EPinContainerType::Array;
}

FName UK2Node_ESQLAsyncGetRows::GetHydrationFunctionName() const
{
	static const FName FunctionName(TEXT("PopulateSQLRowsFromResult"));
	return FunctionName;
}

UK2Node_ESQLAsyncFindRows::UK2Node_ESQLAsyncFindRows(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	static const FName AsyncFindSQLRowsFunctionName(TEXT("AsyncFindSQLRows"));
	ProxyFactoryFunctionName = AsyncFindSQLRowsFunctionName;
	ProxyFactoryClass = ESQLRuntimeReflectionUtils::GetAsyncActionClass(TEXT("ESQLAsyncFindSQLRows"));
	ProxyClass = ProxyFactoryClass;
}

void UK2Node_ESQLAsyncFindRows::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	if (UEdGraphPin* QuerySpecPin = GetQuerySpecPin())
	{
		QuerySpecPin->bHidden = true;
		QuerySpecPin->bAdvancedView = true;
	}

	AllocateQueryClausePins();
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLAsyncFindRows::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLAsyncFindRows::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLAsyncFindRows::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLAsyncFindRows::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	if (HasExplicitValue(GetQuerySpecPin()))
	{
		return;
	}

	ValidateQueryClausePins(MessageLog);
}

void UK2Node_ESQLAsyncFindRows::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	if (UEdGraphPin* QuerySpecPin = GetQuerySpecPin(); QuerySpecPin && !HasExplicitValue(QuerySpecPin))
	{
		if (UEdGraphPin* BuiltQuerySpecPin = BuildQuerySpecPin(CompilerContext, SourceGraph))
		{
			BuiltQuerySpecPin->MakeLinkTo(QuerySpecPin);
		}
	}

	Super::ExpandNode(CompilerContext, SourceGraph);
}

void UK2Node_ESQLAsyncFindRows::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);
	GetQueryClauseContextMenuActions(Menu, Context);
}

void UK2Node_ESQLAsyncFindRows::AddInputPin()
{
	AddFilterClause();
}

bool UK2Node_ESQLAsyncFindRows::CanAddPin() const
{
	return ClauseUiState.NumFilterClauses < MaxClauseCount;
}

void UK2Node_ESQLAsyncFindRows::RemoveInputPin(UEdGraphPin* Pin)
{
	RemoveClauseForPin(Pin);
}

bool UK2Node_ESQLAsyncFindRows::CanRemovePin(const UEdGraphPin* Pin) const
{
	return Pin && IsQueryClausePinName(Pin->PinName);
}

UEdGraphPin* UK2Node_ESQLAsyncFindRows::GetQuerySpecPin() const
{
	return UEdGraphNode::FindPin(ESQLAsyncTypedK2NodePins::QuerySpec);
}

FText UK2Node_ESQLAsyncFindRows::GetMenuTitleText() const
{
	return LOCTEXT("AsyncFindSQLRowsTitle", "Async Find SQL Rows");
}

FText UK2Node_ESQLAsyncFindRows::GetNodeTooltipText() const
{
	return LOCTEXT("AsyncFindSQLRowsTooltip", "Finds typed SQL rows asynchronously using a structured query spec.");
}

FName UK2Node_ESQLAsyncFindRows::GetTypedDataPinName() const
{
	return ESQLAsyncTypedK2NodePins::OutRows;
}

FText UK2Node_ESQLAsyncFindRows::GetTypedDataPinFriendlyName() const
{
	return LOCTEXT("AsyncFindSQLRowsOutFriendlyName", "Rows");
}

FText UK2Node_ESQLAsyncFindRows::GetTypedDataPinDescription() const
{
	return LOCTEXT("AsyncFindSQLRowsOutTooltip", "Typed rows hydrated from the async SQL query result.");
}

EPinContainerType UK2Node_ESQLAsyncFindRows::GetTypedDataPinContainerType() const
{
	return EPinContainerType::Array;
}

FName UK2Node_ESQLAsyncFindRows::GetHydrationFunctionName() const
{
	static const FName FunctionName(TEXT("PopulateSQLRowsFromResult"));
	return FunctionName;
}

UK2Node_ESQLAsyncSaveRow::UK2Node_ESQLAsyncSaveRow(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	static const FName AsyncSaveSQLRowFunctionName(TEXT("AsyncSaveSQLRow"));
	ProxyFactoryFunctionName = AsyncSaveSQLRowFunctionName;
	ProxyFactoryClass = ESQLRuntimeReflectionUtils::GetAsyncActionClass(TEXT("ESQLAsyncSaveSQLRow"));
	ProxyClass = ProxyFactoryClass;
	ProxyActivateFunctionName = GET_FUNCTION_NAME_CHECKED(UBlueprintAsyncActionBase, Activate);
	AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
}

void UK2Node_ESQLAsyncSaveRow::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	if (UEdGraphPin* RowDataPin = GetRowDataPin())
	{
		RowDataPin->PinFriendlyName = LOCTEXT("AsyncSaveSQLRowDataFriendlyName", "Row Data");
		SetPinToolTip(*RowDataPin, LOCTEXT("AsyncSaveSQLRowDataTooltip", "Typed row data to save through the async SQL action."));
	}

	RefreshRowDataPinType();
}

FText UK2Node_ESQLAsyncSaveRow::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return LOCTEXT("AsyncSaveSQLRowTitle", "Async Save SQL Row");
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), LOCTEXT("AsyncSaveSQLRowTitleFmt", "Async Save SQL Row"));
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("AsyncSaveSQLRowAssetTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return LOCTEXT("AsyncSaveSQLRowTitle", "Async Save SQL Row");
}

FText UK2Node_ESQLAsyncSaveRow::GetTooltipText() const
{
	return LOCTEXT("AsyncSaveSQLRowTooltip", "Saves one typed SQL row asynchronously through the SQL async action layer.");
}

void UK2Node_ESQLAsyncSaveRow::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshRowDataPinType();
	}
}

void UK2Node_ESQLAsyncSaveRow::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshRowDataPinType();
}

void UK2Node_ESQLAsyncSaveRow::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLAsyncSaveRow::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLAsyncSaveRow::GetMenuCategory() const
{
	return LOCTEXT("SQLAsyncMenuCategory", "SQL");
}

bool UK2Node_ESQLAsyncSaveRow::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin == GetRowDataPin() && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		const bool bValidStruct = OtherPin->PinType.ContainerType == EPinContainerType::None
			&& (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard);
		if (!bValidStruct)
		{
			OutReason = TEXT("Row Data must connect to a struct");
			return true;
		}
	}

	return Super::IsConnectionDisallowed(MyPin, OtherPin, OutReason);
}

void UK2Node_ESQLAsyncSaveRow::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLAsyncSaveRow::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetRowDataPin())
	{
		RefreshRowDataPinType();
	}
	else if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshRowDataPinType();
	}
}

void UK2Node_ESQLAsyncSaveRow::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || TableAssetPin->LinkedTo.Num() > 0)
	{
		MessageLog.Error(*LOCTEXT("AsyncSaveTypedLiteralTableRequired", "@@ currently requires a literal SQL Table Asset so the async save input can stay typed.").ToString(), this);
		return;
	}

	const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
	if (!TableAsset)
	{
		MessageLog.Error(*LOCTEXT("AsyncSaveMissingTable", "No SQL Table Asset specified in @@").ToString(), this);
		return;
	}

	if (!TableAsset->RowStruct)
	{
		MessageLog.Error(*LOCTEXT("AsyncSaveMissingRowStruct", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
		return;
	}

	if (!ResolveRowStructType())
	{
		MessageLog.Error(*LOCTEXT("AsyncSaveMissingInputType", "@@ could not infer the typed row input. Use a literal SQL Table Asset or connect Row Data to a typed struct.").ToString(), this);
		return;
	}
}

UEdGraphPin* UK2Node_ESQLAsyncSaveRow::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLAsyncTypedK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLAsyncSaveRow::GetRowDataPin() const
{
	return FindPinChecked(ESQLAsyncTypedK2NodePins::RowData);
}

UScriptStruct* UK2Node_ESQLAsyncSaveRow::ResolveRowStructType() const
{
	if (const UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			return const_cast<UScriptStruct*>(TableAsset->RowStruct);
		}
	}

	if (const UEdGraphPin* RowDataPin = GetRowDataPin())
	{
		if (RowDataPin->LinkedTo.Num() > 0)
		{
			for (const UEdGraphPin* LinkedPin : RowDataPin->LinkedTo)
			{
				if (UScriptStruct* LinkedStruct = ExtractStructTypeFromPin(LinkedPin))
				{
					return LinkedStruct;
				}
			}
		}

		return ExtractStructTypeFromPin(RowDataPin);
	}

	return nullptr;
}

void UK2Node_ESQLAsyncSaveRow::RefreshRowDataPinType()
{
	SetRowDataPinType(ResolveRowStructType());
}

void UK2Node_ESQLAsyncSaveRow::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

void UK2Node_ESQLAsyncSaveRow::SetRowDataPinType(UScriptStruct* NewRowStruct)
{
	UEdGraphPin* RowDataPin = GetRowDataPin();
	UScriptStruct* OldRowStruct = ExtractStructTypeFromPin(RowDataPin);
	if (OldRowStruct == NewRowStruct && RowDataPin->PinType.ContainerType == EPinContainerType::None)
	{
		return;
	}

	RowDataPin->PinType.ContainerType = EPinContainerType::None;
	RowDataPin->PinType.PinCategory = NewRowStruct ? UEdGraphSchema_K2::PC_Struct : UEdGraphSchema_K2::PC_Wildcard;
	RowDataPin->PinType.PinSubCategory = NAME_None;
	RowDataPin->PinType.PinSubCategoryObject = NewRowStruct;
	CachedNodeTitle.Clear();
}

void UK2Node_ESQLAsyncSaveRow::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	check(SourceGraph && Schema);

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || TableAssetPin->LinkedTo.Num() > 0 || !TableAssetPin->DefaultObject)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncSaveExpandLiteralTableRequired", "@@ requires a literal SQL Table Asset.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* RowDataPin = GetRowDataPin();
	if (!ResolveRowStructType())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncSaveExpandMissingType", "@@ could not infer the typed row input.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	if (!ProxyFactoryClass || !ProxyClass)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncSaveExpandMissingProxyClass", "@@ could not resolve the internal SQL async action class.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	bool bIsErrorFree = true;
	UK2Node_CallFunction* CallCreateProxyObjectNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallCreateProxyObjectNode->FunctionReference.SetExternalMember(ProxyFactoryFunctionName, ProxyFactoryClass);
	CallCreateProxyObjectNode->AllocateDefaultPins();

	UEdGraphPin* IntermediateRowDataPin = CallCreateProxyObjectNode->FindPinChecked(ESQLAsyncTypedK2NodePins::RowData);
	IntermediateRowDataPin->PinType = RowDataPin->PinType;

	bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *CallCreateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Execute)).CanSafeConnect();

	for (UEdGraphPin* CurrentPin : Pins)
	{
		if (FBaseAsyncTaskHelper::ValidDataPin(CurrentPin, EGPD_Input))
		{
			UEdGraphPin* DestPin = CallCreateProxyObjectNode->FindPin(CurrentPin->PinName);
			if (!DestPin)
			{
				continue;
			}

			if (CurrentPin == TableAssetPin && CurrentPin->LinkedTo.Num() == 0)
			{
				DestPin->DefaultObject = CurrentPin->DefaultObject;
				DestPin->DefaultValue = CurrentPin->DefaultValue;
				DestPin->DefaultTextValue = CurrentPin->DefaultTextValue;
				continue;
			}

			if (CurrentPin == RowDataPin)
			{
				MoveOrCopyPinToIntermediate(CompilerContext, CurrentPin, DestPin);
				continue;
			}

			bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*CurrentPin, *DestPin).CanSafeConnect();
		}
	}

	UEdGraphPin* ProxyObjectPin = CallCreateProxyObjectNode->GetReturnValuePin();
	check(ProxyObjectPin);
	bIsErrorFree &= ExpandDefaultToSelfPin(CompilerContext, SourceGraph, CallCreateProxyObjectNode);

	TArray<FBaseAsyncTaskHelper::FOutputPinAndLocalVariable> VariableOutputs;
	bool bPassedFactoryOutputs = false;
	for (UEdGraphPin* CurrentPin : Pins)
	{
		if (FBaseAsyncTaskHelper::ValidDataPin(CurrentPin, EGPD_Output))
		{
			if (!bPassedFactoryOutputs)
			{
				if (UEdGraphPin* DestPin = CallCreateProxyObjectNode->FindPin(CurrentPin->PinName))
				{
					bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*CurrentPin, *DestPin).CanSafeConnect();
				}
			}
			else
			{
				const FEdGraphPinType& PinType = CurrentPin->PinType;
				UK2Node_TemporaryVariable* TempVarOutput = CompilerContext.SpawnInternalVariable(this, PinType.PinCategory, PinType.PinSubCategory, PinType.PinSubCategoryObject.Get(), PinType.ContainerType, PinType.PinValueType);
				bIsErrorFree &= TempVarOutput->GetVariablePin() && CompilerContext.MovePinLinksToIntermediate(*CurrentPin, *TempVarOutput->GetVariablePin()).CanSafeConnect();
				VariableOutputs.Add(FBaseAsyncTaskHelper::FOutputPinAndLocalVariable(CurrentPin, TempVarOutput));
			}
		}
		else if (!bPassedFactoryOutputs && CurrentPin && CurrentPin->Direction == EGPD_Output)
		{
			bPassedFactoryOutputs = (CurrentPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec) && (CurrentPin->PinName != UEdGraphSchema_K2::PN_Then);
		}
	}

	UEdGraphPin* LastThenPin = CallCreateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Then);

	UK2Node_CallFunction* IsValidFuncNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	IsValidFuncNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, IsValid), UKismetSystemLibrary::StaticClass());
	IsValidFuncNode->AllocateDefaultPins();
	bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, IsValidFuncNode->FindPinChecked(TEXT("Object")));

	UK2Node_IfThenElse* ValidateProxyNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	ValidateProxyNode->AllocateDefaultPins();
	bIsErrorFree &= Schema->TryCreateConnection(IsValidFuncNode->GetReturnValuePin(), ValidateProxyNode->GetConditionPin());
	bIsErrorFree &= Schema->TryCreateConnection(LastThenPin, ValidateProxyNode->GetExecPin());
	LastThenPin = ValidateProxyNode->GetThenPin();

	bIsErrorFree &= HandleDelegates(VariableOutputs, ProxyObjectPin, LastThenPin, SourceGraph, CompilerContext);

	if (CallCreateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Then) == LastThenPin)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncSaveMissingDelegates", "BaseAsyncTask: Proxy has no delegates defined. @@").ToString(), this);
		return;
	}

	if (ProxyActivateFunctionName != NAME_None)
	{
		UK2Node_CallFunction* CallActivateProxyObjectNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		CallActivateProxyObjectNode->FunctionReference.SetExternalMember(ProxyActivateFunctionName, ProxyClass);
		CallActivateProxyObjectNode->AllocateDefaultPins();
		bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, Schema->FindSelfPin(*CallActivateProxyObjectNode, EGPD_Input));
		bIsErrorFree &= Schema->TryCreateConnection(LastThenPin, CallActivateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Execute));
		LastThenPin = CallActivateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Then);
	}

	if (UEdGraphPin* OriginalThenPin = FindPin(UEdGraphSchema_K2::PN_Then))
	{
		bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*OriginalThenPin, *LastThenPin).CanSafeConnect();
	}
	bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*LastThenPin, *ValidateProxyNode->GetElsePin()).CanSafeConnect();

	if (!bIsErrorFree)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("AsyncSaveInternalConnectionError", "BaseAsyncTask: Internal connection error. @@").ToString(), this);
	}

	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE