// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "K2Node/ESQLK2FieldFilterUtils.h"

#include "Blueprint/ESQLBlueprintBridge.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "Shared/ESQLTypes.h"
#include "TableAsset/ESQLTableAsset.h"
#include "UObject/UnrealType.h"

namespace
{
	const UEdGraphPin* FindPinByName(const UEdGraphNode* Node, const FName PinName)
	{
		return Node ? Node->FindPin(PinName) : nullptr;
	}

	UEdGraphPin* FindPinByName(UEdGraphNode* Node, const FName PinName)
	{
		return Node ? Node->FindPin(PinName) : nullptr;
	}

	FName ResolveLiteralFieldName(const UEdGraphNode* Node, const FName FieldNamePinName)
	{
		const UEdGraphPin* FieldNamePin = FindPinByName(Node, FieldNamePinName);
		if (!FieldNamePin || FieldNamePin->LinkedTo.Num() > 0)
		{
			return NAME_None;
		}

		FString DefaultValue = FieldNamePin->GetDefaultAsString();
		DefaultValue.TrimStartAndEndInline();
		DefaultValue.RemoveFromStart(TEXT("\""));
		DefaultValue.RemoveFromEnd(TEXT("\""));
		return DefaultValue.IsEmpty() ? NAME_None : FName(*DefaultValue);
	}

	FEdGraphPinType MakeBindingValuePinType()
	{
		FEdGraphPinType PinType;
		PinType.ContainerType = EPinContainerType::None;
		PinType.PinCategory = UEdGraphSchema_K2::PC_Struct;
		PinType.PinSubCategory = NAME_None;
		PinType.PinSubCategoryObject = FESQLBindingValue::StaticStruct();
		PinType.PinValueType.TerminalCategory = NAME_None;
		PinType.PinValueType.TerminalSubCategory = NAME_None;
		PinType.PinValueType.TerminalSubCategoryObject = nullptr;
		return PinType;
	}

	bool TryConvertFieldPropertyToPinType(const FProperty* FieldProperty, FEdGraphPinType& OutPinType)
	{
		if (!FieldProperty || FieldProperty->ArrayDim != 1)
		{
			return false;
		}

		if (CastField<FArrayProperty>(FieldProperty) || CastField<FSetProperty>(FieldProperty) || CastField<FMapProperty>(FieldProperty))
		{
			return false;
		}

		const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();
		return K2Schema && K2Schema->ConvertPropertyToPinType(FieldProperty, OutPinType);
	}

	void MoveOrCopyPinToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	}
}

UESQLTableAsset* ESQLK2FieldFilterUtils::ResolveLiteralTableAsset(const UEdGraphNode* Node, const FName TableAssetPinName)
{
	const UEdGraphPin* TableAssetPin = FindPinByName(Node, TableAssetPinName);
	if (!TableAssetPin || TableAssetPin->LinkedTo.Num() > 0)
	{
		return nullptr;
	}

	return Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
}

const FProperty* ESQLK2FieldFilterUtils::ResolveLiteralFieldProperty(const UEdGraphNode* Node, const FName TableAssetPinName, const FName FieldNamePinName)
{
	const UESQLTableAsset* TableAsset = ResolveLiteralTableAsset(Node, TableAssetPinName);
	if (!TableAsset || !TableAsset->RowStruct)
	{
		return nullptr;
	}

	const FName FieldName = ResolveLiteralFieldName(Node, FieldNamePinName);
	if (FieldName.IsNone())
	{
		return nullptr;
	}

	const FString FieldNameString = FieldName.ToString();
	for (TFieldIterator<FProperty> PropertyIt(TableAsset->RowStruct, EFieldIteratorFlags::ExcludeSuper); PropertyIt; ++PropertyIt)
	{
		const FProperty* Property = *PropertyIt;
		if (!Property)
		{
			continue;
		}

		if (Property->GetFName() == FieldName || Property->GetName() == FieldNameString || Property->GetAuthoredName() == FieldNameString)
		{
			return Property;
		}
	}

	return nullptr;
}

void ESQLK2FieldFilterUtils::ApplyFieldValuePinType(UEdGraphPin& ValuePin, const FProperty* FieldProperty)
{
	FEdGraphPinType NewPinType;
	if (!TryConvertFieldPropertyToPinType(FieldProperty, NewPinType))
	{
		NewPinType = MakeBindingValuePinType();
	}

	if (ValuePin.PinType == NewPinType)
	{
		return;
	}

	if (ValuePin.SubPins.Num() > 0)
	{
		if (UEdGraphNode* OwningNode = ValuePin.GetOwningNodeUnchecked())
		{
			if (const UEdGraphSchema* Schema = OwningNode->GetSchema())
			{
				Schema->RecombinePin(&ValuePin);
			}
		}
	}

	ValuePin.PinType = NewPinType;
	if (ValuePin.LinkedTo.Num() == 0)
	{
		if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
		{
			K2Schema->SetPinAutogeneratedDefaultValueBasedOnType(&ValuePin);
		}
	}
}

bool ESQLK2FieldFilterUtils::IsBindingValuePin(const UEdGraphPin* Pin)
{
	return Pin
		&& Pin->PinType.ContainerType == EPinContainerType::None
		&& Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct
		&& Pin->PinType.PinSubCategoryObject == FESQLBindingValue::StaticStruct();
}

void ESQLK2FieldFilterUtils::CollectFieldNameOptions(const UEdGraphNode* Node, const FName TableAssetPinName, TArray<TSharedPtr<FName>>& OutOptions)
{
	OutOptions.Reset();

	const UESQLTableAsset* TableAsset = ResolveLiteralTableAsset(Node, TableAssetPinName);
	if (!TableAsset || !TableAsset->RowStruct)
	{
		return;
	}

	TSet<FString> AddedFieldNames;
	for (TFieldIterator<FProperty> PropertyIt(TableAsset->RowStruct, EFieldIteratorFlags::ExcludeSuper); PropertyIt; ++PropertyIt)
	{
		const FProperty* Property = *PropertyIt;
		if (!Property)
		{
			continue;
		}

		FString DisplayName = Property->GetAuthoredName();
		if (DisplayName.IsEmpty())
		{
			DisplayName = Property->GetName();
		}

		if (AddedFieldNames.Contains(DisplayName))
		{
			continue;
		}

		AddedFieldNames.Add(DisplayName);
		OutOptions.Add(MakeShared<FName>(*DisplayName));
	}

	OutOptions.Sort([](const TSharedPtr<FName>& Left, const TSharedPtr<FName>& Right)
	{
		const FString LeftString = Left.IsValid() ? Left->ToString() : FString();
		const FString RightString = Right.IsValid() ? Right->ToString() : FString();
		return LeftString < RightString;
	});
}

void ESQLK2FieldFilterUtils::MoveValuePinToBindingPin(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node* SourceNode, UEdGraphPin* ValuePin, UEdGraphPin* TargetBindingPin)
{
	if (!ValuePin || !TargetBindingPin || !SourceNode)
	{
		return;
	}

	if (IsBindingValuePin(ValuePin))
	{
		MoveOrCopyPinToIntermediate(CompilerContext, ValuePin, TargetBindingPin);
		return;
	}

	UK2Node_CallFunction* ConversionNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(SourceNode, SourceGraph);
	ConversionNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, MakeSQLBindingValue), UESQLBlueprintBridge::StaticClass());
	ConversionNode->AllocateDefaultPins();

	UEdGraphPin* ConversionValuePin = FindPinByName(ConversionNode, TEXT("Value"));
	if (ConversionValuePin)
	{
		ConversionValuePin->PinType = ValuePin->PinType;
		MoveOrCopyPinToIntermediate(CompilerContext, ValuePin, ConversionValuePin);
	}

	if (UEdGraphPin* ReturnValuePin = ConversionNode->GetReturnValuePin())
	{
		ReturnValuePin->MakeLinkTo(TargetBindingPin);
	}
}