// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "K2Node/ESQLPlayerTypedK2Nodes.h"

#include "Blueprint/ESQLBlueprintBridge.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Misc/OutputDeviceNull.h"
#include "PlayerData/ESQLPlayerDBComponent.h"
#include "Shared/ESQLId.h"
#include "Styling/AppStyle.h"
#include "TableAsset/ESQLTableAsset.h"
#include "UObject/PropertyPortFlags.h"

#define LOCTEXT_NAMESPACE "ESQLPlayerTypedK2Nodes"

namespace ESQLPlayerTypedK2NodePins
{
	const FName PlayerDBComponent(TEXT("PlayerDBComponent"));
	const FName TableAsset(TEXT("TableAsset"));
	const FName RowId(TEXT("RowId"));
	const FName SqlId(TEXT("SqlId"));
	const FName OutRow(TEXT("OutRow"));
	const FName RowData(TEXT("RowData"));
	const FName RowIdOverride(TEXT("RowIdOverride"));
	const FName OutResolvedRowId(TEXT("OutResolvedRowId"));
	const FName Result(TEXT("Result"));
	const FName OutRows(TEXT("OutRows"));
	const FName MaxRows(TEXT("MaxRows"));
	const FName QuerySpec(TEXT("QuerySpec"));
}

namespace
{
	bool ShouldRegisterBlueprintAction(const UClass* NodeClass)
	{
		return NodeClass && !NodeClass->HasMetaData(TEXT("ESQLHideFromBlueprintPalette"));
	}

	const UEdGraphPin* FindPinByName(const TArray<UEdGraphPin*>& PinsToSearch, const FName PinName)
	{
		for (const UEdGraphPin* Pin : PinsToSearch)
		{
			if (Pin && Pin->PinName == PinName)
			{
				return Pin;
			}
		}

		return nullptr;
	}

	UScriptStruct* ExtractStructTypeFromPin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.ContainerType != EPinContainerType::None)
		{
			return nullptr;
		}

		if (Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
		{
			return nullptr;
		}

		return Cast<UScriptStruct>(Pin->PinType.PinSubCategoryObject.Get());
	}

	UScriptStruct* ExtractStructTypeFromArrayPin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.ContainerType != EPinContainerType::Array)
		{
			return nullptr;
		}

		if (Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
		{
			return nullptr;
		}

		return Cast<UScriptStruct>(Pin->PinType.PinSubCategoryObject.Get());
	}

	bool IsESQLIdStructPin(const UEdGraphPin* Pin)
	{
		const UScriptStruct* PinStruct = ExtractStructTypeFromPin(Pin);
		const UScriptStruct* SqlIdStruct = FESQLId::StaticStruct();
		return PinStruct
			&& SqlIdStruct
			&& (PinStruct == SqlIdStruct || PinStruct->GetName().Contains(SqlIdStruct->GetName(), ESearchCase::IgnoreCase));
	}

	void MoveOrCopyPinToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	}

	bool HasExplicitValue(const UEdGraphPin* Pin)
	{
		if (!Pin)
		{
			return false;
		}

		if (Pin->LinkedTo.Num() > 0)
		{
			return true;
		}

		return !Pin->DefaultValue.IsEmpty() && Pin->DefaultValue != Pin->AutogeneratedDefaultValue;
	}

	bool TryGetSqlIdFromStructDefault(const UEdGraphPin* Pin, FESQLId& OutSqlId)
	{
		OutSqlId = FESQLId();
		if (!Pin
			|| Pin->LinkedTo.Num() > 0
			|| !IsESQLIdStructPin(Pin))
		{
			return false;
		}

		const FString DefaultValue = Pin->GetDefaultAsString();
		if (DefaultValue.IsEmpty())
		{
			return false;
		}

		FOutputDeviceNull NullOutput;
		FESQLId::StaticStruct()->ImportText(*DefaultValue, &OutSqlId, nullptr, PPF_SerializedAsImportText, &NullOutput, Pin->PinName.ToString());
		return !OutSqlId.Value.IsEmpty();
	}

	bool TryGetLegacyStringPinValue(const UEdGraphPin* Pin, FString& OutValue)
	{
		OutValue.Reset();
		if (!Pin || Pin->LinkedTo.Num() > 0 || Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_String)
		{
			return false;
		}

		OutValue = Pin->GetDefaultAsString();
		OutValue.TrimStartAndEndInline();
		OutValue.RemoveFromStart(TEXT("\""));
		OutValue.RemoveFromEnd(TEXT("\""));
		return !OutValue.IsEmpty();
	}

	void ApplySqlIdToPinDefault(UEdGraphPin* Pin, const FESQLId& SqlId)
	{
		if (!Pin)
		{
			return;
		}

		FString ExportText;
		FESQLId::StaticStruct()->ExportText(ExportText, &SqlId, &SqlId, nullptr, PPF_SerializedAsImportText, nullptr);
		Pin->DefaultValue = ExportText;
		Pin->AutogeneratedDefaultValue = ExportText;
		Pin->DefaultTextValue = FText::GetEmpty();
		Pin->DefaultObject = nullptr;
	}

	void UpgradeLegacyStringRowIdPin(const TArray<UEdGraphPin*>& OldPins, const FName PinName, UEdGraphPin* NewPin, UESQLTableAsset* TableAsset)
	{
		const UEdGraphPin* OldPin = FindPinByName(OldPins, PinName);
		if (!OldPin || !NewPin)
		{
			return;
		}

		FString LegacyValue;
		if (!TryGetLegacyStringPinValue(OldPin, LegacyValue))
		{
			return;
		}

		FESQLId SqlId(LegacyValue);
		if (TableAsset)
		{
			SqlId.SourceTable = TableAsset;
		}

		ApplySqlIdToPinDefault(NewPin, SqlId);
	}
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* PlayerDBPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLPlayerDBComponent::StaticClass(), ESQLPlayerTypedK2NodePins::PlayerDBComponent);
	PlayerDBPin->PinFriendlyName = LOCTEXT("PlayerDBFriendlyName", "Player DB");
	SetPinToolTip(*PlayerDBPin, LOCTEXT("PlayerDBTooltip", "Explicit player database component that owns the player-scoped SQL data."));

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLPlayerTypedK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("PlayerTableAssetFriendlyName", "Table Asset");
	SetPinToolTip(*TableAssetPin, LOCTEXT("PlayerTableAssetTooltip", "The SQL table asset that owns the row struct and schema metadata."));

	AllocateOperationPins();

	UEdGraphPin* TypedRowPin = CreatePin(GetTypedRowPinDirection(), UEdGraphSchema_K2::PC_Wildcard, GetTypedRowPinName());
	TypedRowPin->PinFriendlyName = GetTypedRowPinFriendlyName();
	SetPinToolTip(*TypedRowPin, GetTypedRowPinDescription());

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLPlayerTypedK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("PlayerResultFriendlyName", "Result");
	SetPinToolTip(*ResultPin, LOCTEXT("PlayerResultTooltip", "Raw SQL query result for success state, rows, and error details."));

	Super::AllocateDefaultPins();
	RefreshTypedRowPinType();
}

bool UK2Node_ESQLPlayerTypedRowBridgeBase::CanSplitPin(const UEdGraphPin* Pin) const
{
	return !IsESQLIdStructPin(Pin) && Super::CanSplitPin(Pin);
}

FText UK2Node_ESQLPlayerTypedRowBridgeBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return GetMenuTitleText();
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), GetMenuTitleText());
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("PlayerTypedAssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return GetMenuTitleText();
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshTypedRowPinType();
	}
}

FText UK2Node_ESQLPlayerTypedRowBridgeBase::GetTooltipText() const
{
	return GetNodeTooltipText();
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* PlayerDBPin = GetPlayerDBPin();
	if (!PlayerDBPin || (PlayerDBPin->LinkedTo.Num() == 0 && PlayerDBPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingPlayerDBOnExpand", "@@ must have a Player DB Component specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingPlayerTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	if (!ResolveRowStructType())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingPlayerRowTypeOnExpand", "@@ could not infer a typed row struct. Use a literal Table Asset or connect the row pin to a typed struct.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* BridgeCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	BridgeCallNode->FunctionReference.SetExternalMember(GetBridgeFunctionName(), UESQLBlueprintBridge::StaticClass());
	BridgeCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *BridgeCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *BridgeCallNode->GetThenPin());

	MoveOrCopyPinToIntermediate(CompilerContext, PlayerDBPin, BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::PlayerDBComponent));
	MoveOrCopyPinToIntermediate(CompilerContext, TableAssetPin, BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::TableAsset));

	ExpandOperationPins(CompilerContext, SourceGraph, BridgeCallNode);

	UEdGraphPin* TypedRowPin = GetTypedRowPin();
	UEdGraphPin* BridgeTypedRowPin = BridgeCallNode->FindPinChecked(GetTypedRowPinName());
	BridgeTypedRowPin->PinType = TypedRowPin->PinType;
	if (GetTypedRowPinDirection() == EGPD_Output)
	{
		CompilerContext.MovePinLinksToIntermediate(*TypedRowPin, *BridgeTypedRowPin);
	}
	else
	{
		MoveOrCopyPinToIntermediate(CompilerContext, TypedRowPin, BridgeTypedRowPin);
	}

	CompilerContext.MovePinLinksToIntermediate(*GetQueryResultPin(), *BridgeCallNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLPlayerTypedRowBridgeBase::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshTypedRowPinType();
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	UpgradeLegacyStringRowIdPin(OldPins, ESQLPlayerTypedK2NodePins::RowId, FindPin(ESQLPlayerTypedK2NodePins::RowId), Cast<UESQLTableAsset>(GetTableAssetPin() ? GetTableAssetPin()->DefaultObject : nullptr));
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLPlayerTypedRowBridgeBase::GetMenuCategory() const
{
	return LOCTEXT("PlayerSQLMenuCategory", "SQL|Player");
}

bool UK2Node_ESQLPlayerTypedRowBridgeBase::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin == GetTypedRowPin() && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		const bool bValidStruct = OtherPin->PinType.ContainerType == EPinContainerType::None
			&& (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard);
		if (!bValidStruct)
		{
			OutReason = TEXT("Row pin must connect to a struct");
			return true;
		}
	}

	return false;
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PlayerDBPin = GetPlayerDBPin();
	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	const UEdGraphPin* TypedRowPin = GetTypedRowPin();
	if (!PlayerDBPin || !TableAssetPin || !TypedRowPin)
	{
		MessageLog.Error(*LOCTEXT("MissingPlayerTypedPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (PlayerDBPin->LinkedTo.Num() == 0 && PlayerDBPin->DefaultObject == nullptr)
	{
		MessageLog.Error(*LOCTEXT("NoPlayerDBError", "No Player DB Component specified in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0)
	{
		const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
		if (!TableAsset)
		{
			MessageLog.Error(*LOCTEXT("NoPlayerTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
			return;
		}

		if (!TableAsset->RowStruct)
		{
			MessageLog.Error(*LOCTEXT("PlayerMissingRowStructError", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
			return;
		}
	}

	if (!ResolveRowStructType())
	{
		MessageLog.Error(*LOCTEXT("UnresolvedPlayerRowStructError", "@@ could not infer the row struct type. Use a literal Table Asset or connect the row pin to a typed struct.").ToString(), this);
		return;
	}

	ValidateOperationPins(MessageLog);
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetTypedRowPin())
	{
		const UEdGraphPin* TableAssetPin = GetTableAssetPin();
		const bool bTypedRowAuthority = TableAssetPin && (TableAssetPin->LinkedTo.Num() > 0 || TableAssetPin->DefaultObject == nullptr);
		if (bTypedRowAuthority)
		{
			RefreshTypedRowPinType();
		}
	}
	else if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshTypedRowPinType();
	}
}

UEdGraphPin* UK2Node_ESQLPlayerTypedRowBridgeBase::GetPlayerDBPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLPlayerTypedK2NodePins::PlayerDBComponent)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLPlayerTypedRowBridgeBase::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLPlayerTypedK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLPlayerTypedRowBridgeBase::GetTypedRowPin() const
{
	return FindPinChecked(GetTypedRowPinName());
}

UEdGraphPin* UK2Node_ESQLPlayerTypedRowBridgeBase::GetQueryResultPin() const
{
	return FindPinChecked(ESQLPlayerTypedK2NodePins::Result);
}

UScriptStruct* UK2Node_ESQLPlayerTypedRowBridgeBase::ResolveRowStructType() const
{
	if (const UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (TableAssetPin->LinkedTo.Num() == 0)
		{
			if (const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
			{
				return const_cast<UScriptStruct*>(TableAsset->RowStruct);
			}
		}
	}

	if (const UEdGraphPin* TypedRowPin = GetTypedRowPin())
	{
		if (TypedRowPin->LinkedTo.Num() > 0)
		{
			for (const UEdGraphPin* LinkedPin : TypedRowPin->LinkedTo)
			{
				if (UScriptStruct* LinkedStruct = ExtractStructTypeFromPin(LinkedPin))
				{
					return LinkedStruct;
				}
			}
		}

		return ExtractStructTypeFromPin(TypedRowPin);
	}

	return nullptr;
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::RefreshTypedRowPinType()
{
	SetTypedRowPinType(ResolveRowStructType());
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::SetTypedRowPinType(UScriptStruct* NewRowStruct)
{
	UEdGraphPin* TypedRowPin = GetTypedRowPin();
	UScriptStruct* OldRowStruct = ExtractStructTypeFromPin(TypedRowPin);
	if (OldRowStruct == NewRowStruct && TypedRowPin->PinType.ContainerType == EPinContainerType::None)
	{
		return;
	}

	if (TypedRowPin->SubPins.Num() > 0)
	{
		GetSchema()->RecombinePin(TypedRowPin);
	}

	TypedRowPin->PinType.ContainerType = EPinContainerType::None;
	TypedRowPin->PinType.PinCategory = NewRowStruct ? UEdGraphSchema_K2::PC_Struct : UEdGraphSchema_K2::PC_Wildcard;
	TypedRowPin->PinType.PinSubCategory = NAME_None;
	TypedRowPin->PinType.PinSubCategoryObject = NewRowStruct;
	CachedNodeTitle.Clear();
}

void UK2Node_ESQLPlayerTypedRowBridgeBase::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

FName UK2Node_ESQLGetPlayerRow::GetBridgeFunctionName() const
{
	return GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, LoadPlayerSQLRow);
}

FText UK2Node_ESQLGetPlayerRow::GetMenuTitleText() const
{
	return LOCTEXT("GetPlayerSQLRowMenuTitle", "Get Player SQL Row");
}

FText UK2Node_ESQLGetPlayerRow::GetNodeTooltipText() const
{
	return LOCTEXT("GetPlayerSQLRowTooltip", "Loads one typed row from a player-scoped SQL table through the runtime SQL bridge.");
}

FName UK2Node_ESQLGetPlayerRow::GetTypedRowPinName() const
{
	return ESQLPlayerTypedK2NodePins::OutRow;
}

FText UK2Node_ESQLGetPlayerRow::GetTypedRowPinFriendlyName() const
{
	return LOCTEXT("GetPlayerSQLRowFriendlyName", "Row");
}

FText UK2Node_ESQLGetPlayerRow::GetTypedRowPinDescription() const
{
	return LOCTEXT("GetPlayerSQLRowDescription", "Typed row loaded from the player-scoped SQL table.");
}

EEdGraphPinDirection UK2Node_ESQLGetPlayerRow::GetTypedRowPinDirection() const
{
	return EGPD_Output;
}

void UK2Node_ESQLGetPlayerRow::AllocateOperationPins()
{
	UEdGraphPin* RowIdPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLId::StaticStruct(), ESQLPlayerTypedK2NodePins::RowId);
	RowIdPin->PinFriendlyName = LOCTEXT("GetPlayerSQLRowIdFriendlyName", "SQL Id");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(RowIdPin);
	SetPinToolTip(*RowIdPin, LOCTEXT("GetPlayerSQLRowIdTooltip", "SQL identifier that provides the player row id value for the typed row lookup."));
}

void UK2Node_ESQLGetPlayerRow::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLPlayerTypedK2NodePins::RowId), FunctionNode->FindPinChecked(ESQLPlayerTypedK2NodePins::SqlId));
}

void UK2Node_ESQLGetPlayerRow::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	const UEdGraphPin* RowIdPin = FindPinChecked(ESQLPlayerTypedK2NodePins::RowId);
	FESQLId SqlId;
	if (RowIdPin->LinkedTo.Num() == 0 && !TryGetSqlIdFromStructDefault(RowIdPin, SqlId))
	{
		MessageLog.Error(*LOCTEXT("MissingPlayerRowIdError", "@@ requires an SQL Id when the pin is not linked.").ToString(), this);
	}
}

FName UK2Node_ESQLSavePlayerRow::GetBridgeFunctionName() const
{
	return GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, SavePlayerSQLRow);
}

FText UK2Node_ESQLSavePlayerRow::GetMenuTitleText() const
{
	return LOCTEXT("SavePlayerSQLRowMenuTitle", "Save Player SQL Row");
}

FText UK2Node_ESQLSavePlayerRow::GetNodeTooltipText() const
{
	return LOCTEXT("SavePlayerSQLRowTooltip", "Saves one typed row through a player-scoped SQL table and resolves the final row id through the runtime SQL bridge.");
}

FName UK2Node_ESQLSavePlayerRow::GetTypedRowPinName() const
{
	return ESQLPlayerTypedK2NodePins::RowData;
}

FText UK2Node_ESQLSavePlayerRow::GetTypedRowPinFriendlyName() const
{
	return LOCTEXT("SavePlayerSQLRowFriendlyName", "Row");
}

FText UK2Node_ESQLSavePlayerRow::GetTypedRowPinDescription() const
{
	return LOCTEXT("SavePlayerSQLRowDescription", "Typed row data to save into the player-scoped SQL table.");
}

EEdGraphPinDirection UK2Node_ESQLSavePlayerRow::GetTypedRowPinDirection() const
{
	return EGPD_Input;
}

void UK2Node_ESQLSavePlayerRow::AllocateOperationPins()
{
	UEdGraphPin* RowIdOverridePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, ESQLPlayerTypedK2NodePins::RowIdOverride);
	RowIdOverridePin->PinFriendlyName = LOCTEXT("SavePlayerSQLRowIdOverrideFriendlyName", "Row Id Override");
	SetPinToolTip(*RowIdOverridePin, LOCTEXT("SavePlayerSQLRowIdOverrideTooltip", "Optional explicit row id to use for the save operation."));

	UEdGraphPin* ResolvedRowIdPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_String, ESQLPlayerTypedK2NodePins::OutResolvedRowId);
	ResolvedRowIdPin->PinFriendlyName = LOCTEXT("SavePlayerResolvedRowIdFriendlyName", "Resolved Row Id");
	SetPinToolTip(*ResolvedRowIdPin, LOCTEXT("SavePlayerResolvedRowIdTooltip", "Final row id returned by the player-scoped save operation."));
}

void UK2Node_ESQLSavePlayerRow::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLPlayerTypedK2NodePins::RowIdOverride), FunctionNode->FindPinChecked(ESQLPlayerTypedK2NodePins::RowIdOverride));
	CompilerContext.MovePinLinksToIntermediate(*GetResolvedRowIdPin(), *FunctionNode->FindPinChecked(ESQLPlayerTypedK2NodePins::OutResolvedRowId));
}

UEdGraphPin* UK2Node_ESQLSavePlayerRow::GetResolvedRowIdPin() const
{
	return FindPinChecked(ESQLPlayerTypedK2NodePins::OutResolvedRowId);
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* PlayerDBPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLPlayerDBComponent::StaticClass(), ESQLPlayerTypedK2NodePins::PlayerDBComponent);
	PlayerDBPin->PinFriendlyName = LOCTEXT("PlayerArrayDBFriendlyName", "Player DB");
	SetPinToolTip(*PlayerDBPin, LOCTEXT("PlayerArrayDBTooltip", "Explicit player database component that owns the player-scoped SQL data."));

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLPlayerTypedK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("PlayerArrayTableAssetFriendlyName", "Table Asset");
	SetPinToolTip(*TableAssetPin, LOCTEXT("PlayerArrayTableAssetTooltip", "The SQL table asset that owns the row struct and schema metadata."));

	AllocateOperationPins();

	UEdGraphNode::FCreatePinParams RowsPinParams;
	RowsPinParams.ContainerType = EPinContainerType::Array;
	UEdGraphPin* RowsPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Wildcard, ESQLPlayerTypedK2NodePins::OutRows, RowsPinParams);
	RowsPin->PinFriendlyName = LOCTEXT("PlayerRowsFriendlyName", "Rows");
	SetPinToolTip(*RowsPin, LOCTEXT("PlayerRowsTooltip", "Typed rows loaded from the player-scoped SQL table."));

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLPlayerTypedK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("PlayerArrayResultFriendlyName", "Result");
	SetPinToolTip(*ResultPin, LOCTEXT("PlayerArrayResultTooltip", "Raw SQL query result for success state, rows, and error details."));

	Super::AllocateDefaultPins();
	RefreshRowsPinType();
}

FText UK2Node_ESQLPlayerRowArrayBridgeBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return GetMenuTitleText();
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), GetMenuTitleText());
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("PlayerArrayAssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return GetMenuTitleText();
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshRowsPinType();
	}
}

FText UK2Node_ESQLPlayerRowArrayBridgeBase::GetTooltipText() const
{
	return GetNodeTooltipText();
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* PlayerDBPin = GetPlayerDBPin();
	if (!PlayerDBPin || (PlayerDBPin->LinkedTo.Num() == 0 && PlayerDBPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingPlayerDBArrayOnExpand", "@@ must have a Player DB Component specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingPlayerArrayTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	if (!ResolveRowStructType())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingPlayerArrayRowTypeOnExpand", "@@ could not infer a typed row array output. Use a literal Table Asset or connect Rows to a typed struct array.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* BridgeCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	BridgeCallNode->FunctionReference.SetExternalMember(GetBridgeFunctionName(), UESQLBlueprintBridge::StaticClass());
	BridgeCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *BridgeCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *BridgeCallNode->GetThenPin());

	MoveOrCopyPinToIntermediate(CompilerContext, PlayerDBPin, BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::PlayerDBComponent));
	MoveOrCopyPinToIntermediate(CompilerContext, TableAssetPin, BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::TableAsset));

	ExpandOperationPins(CompilerContext, SourceGraph, BridgeCallNode);

	UEdGraphPin* RowsPin = GetRowsPin();
	UEdGraphPin* BridgeRowsPin = BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::OutRows);
	BridgeRowsPin->PinType = RowsPin->PinType;
	CompilerContext.MovePinLinksToIntermediate(*RowsPin, *BridgeRowsPin);
	CompilerContext.MovePinLinksToIntermediate(*GetQueryResultPin(), *BridgeCallNode->GetReturnValuePin());

	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLPlayerRowArrayBridgeBase::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshRowsPinType();
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (!ShouldRegisterBlueprintAction(GetClass()))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLPlayerRowArrayBridgeBase::GetMenuCategory() const
{
	return LOCTEXT("PlayerArraySQLMenuCategory", "SQL|Player");
}

bool UK2Node_ESQLPlayerRowArrayBridgeBase::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin == GetRowsPin() && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		const bool bValidStructArray = OtherPin->PinType.ContainerType == EPinContainerType::Array
			&& (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct || OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard);
		if (!bValidStructArray)
		{
			OutReason = TEXT("Rows must connect to an array of structs");
			return true;
		}
	}

	return false;
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PlayerDBPin = GetPlayerDBPin();
	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	const UEdGraphPin* RowsPin = GetRowsPin();
	if (!PlayerDBPin || !TableAssetPin || !RowsPin)
	{
		MessageLog.Error(*LOCTEXT("MissingPlayerArrayPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (PlayerDBPin->LinkedTo.Num() == 0 && PlayerDBPin->DefaultObject == nullptr)
	{
		MessageLog.Error(*LOCTEXT("NoPlayerDBArrayError", "No Player DB Component specified in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0)
	{
		const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject);
		if (!TableAsset)
		{
			MessageLog.Error(*LOCTEXT("NoPlayerArrayTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
			return;
		}

		if (!TableAsset->RowStruct)
		{
			MessageLog.Error(*LOCTEXT("PlayerArrayMissingRowStructError", "SQL Table Asset in @@ does not define a RowStruct").ToString(), this);
			return;
		}
	}

	if (!ResolveRowStructType())
	{
		MessageLog.Error(*LOCTEXT("UnresolvedPlayerArrayRowStructError", "@@ could not infer the output row type. Use a literal Table Asset or connect Rows to a typed struct array.").ToString(), this);
		return;
	}

	ValidateOperationPins(MessageLog);
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetRowsPin())
	{
		const UEdGraphPin* TableAssetPin = GetTableAssetPin();
		const bool bRowsAuthority = TableAssetPin && (TableAssetPin->LinkedTo.Num() > 0 || TableAssetPin->DefaultObject == nullptr);
		if (bRowsAuthority)
		{
			RefreshRowsPinType();
		}
	}
	else if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
		RefreshRowsPinType();
	}
}

UEdGraphPin* UK2Node_ESQLPlayerRowArrayBridgeBase::GetPlayerDBPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLPlayerTypedK2NodePins::PlayerDBComponent)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLPlayerRowArrayBridgeBase::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLPlayerTypedK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLPlayerRowArrayBridgeBase::GetRowsPin() const
{
	return FindPinChecked(ESQLPlayerTypedK2NodePins::OutRows);
}

UEdGraphPin* UK2Node_ESQLPlayerRowArrayBridgeBase::GetQueryResultPin() const
{
	return FindPinChecked(ESQLPlayerTypedK2NodePins::Result);
}

UScriptStruct* UK2Node_ESQLPlayerRowArrayBridgeBase::ResolveRowStructType() const
{
	if (const UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (TableAssetPin->LinkedTo.Num() == 0)
		{
			if (const UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
			{
				return const_cast<UScriptStruct*>(TableAsset->RowStruct);
			}
		}
	}

	if (const UEdGraphPin* RowsPin = GetRowsPin())
	{
		if (RowsPin->LinkedTo.Num() > 0)
		{
			for (const UEdGraphPin* LinkedPin : RowsPin->LinkedTo)
			{
				if (UScriptStruct* LinkedStruct = ExtractStructTypeFromArrayPin(LinkedPin))
				{
					return LinkedStruct;
				}
			}
		}

		return ExtractStructTypeFromArrayPin(RowsPin);
	}

	return nullptr;
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::RefreshRowsPinType()
{
	SetRowsPinType(ResolveRowStructType());
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::SetRowsPinType(UScriptStruct* NewRowStruct)
{
	UEdGraphPin* RowsPin = GetRowsPin();
	UScriptStruct* OldRowStruct = ExtractStructTypeFromArrayPin(RowsPin);
	if (OldRowStruct == NewRowStruct && RowsPin->PinType.ContainerType == EPinContainerType::Array)
	{
		return;
	}

	RowsPin->PinType.ContainerType = EPinContainerType::Array;
	RowsPin->PinType.PinCategory = NewRowStruct ? UEdGraphSchema_K2::PC_Struct : UEdGraphSchema_K2::PC_Wildcard;
	RowsPin->PinType.PinSubCategory = NAME_None;
	RowsPin->PinType.PinSubCategoryObject = NewRowStruct;
	CachedNodeTitle.Clear();
}

void UK2Node_ESQLPlayerRowArrayBridgeBase::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

FName UK2Node_ESQLGetPlayerRows::GetBridgeFunctionName() const
{
	return GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, LoadPlayerSQLRows);
}

FText UK2Node_ESQLGetPlayerRows::GetMenuTitleText() const
{
	return LOCTEXT("GetPlayerSQLRowsMenuTitle", "Get Player SQL Rows");
}

FText UK2Node_ESQLGetPlayerRows::GetNodeTooltipText() const
{
	return LOCTEXT("GetPlayerSQLRowsTooltip", "Loads typed rows from a player-scoped SQL table through the runtime SQL bridge.");
}

void UK2Node_ESQLGetPlayerRows::AllocateOperationPins()
{
	UEdGraphPin* MaxRowsPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, ESQLPlayerTypedK2NodePins::MaxRows);
	MaxRowsPin->PinFriendlyName = LOCTEXT("GetPlayerMaxRowsFriendlyName", "Max Rows");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(MaxRowsPin);
	SetPinToolTip(*MaxRowsPin, LOCTEXT("GetPlayerMaxRowsTooltip", "Optional limit for how many player rows should be loaded."));
}

void UK2Node_ESQLGetPlayerRows::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(ESQLPlayerTypedK2NodePins::MaxRows), FunctionNode->FindPinChecked(ESQLPlayerTypedK2NodePins::MaxRows));
}

FName UK2Node_ESQLFindPlayerRows::GetBridgeFunctionName() const
{
	return GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, FindPlayerSQLRows);
}

FText UK2Node_ESQLFindPlayerRows::GetMenuTitleText() const
{
	return LOCTEXT("FindPlayerSQLRowsMenuTitle", "Find Player SQL Rows");
}

FText UK2Node_ESQLFindPlayerRows::GetNodeTooltipText() const
{
	return LOCTEXT("FindPlayerSQLRowsTooltip", "Finds typed rows from a player-scoped SQL table using a structured query spec through the runtime SQL bridge.");
}

void UK2Node_ESQLFindPlayerRows::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLFindPlayerRows::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLFindPlayerRows::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLFindPlayerRows::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);
	GetQueryClauseContextMenuActions(Menu, Context);
}

void UK2Node_ESQLFindPlayerRows::AddInputPin()
{
	AddFilterClause();
}

bool UK2Node_ESQLFindPlayerRows::CanAddPin() const
{
	return ClauseUiState.NumFilterClauses < MaxClauseCount;
}

void UK2Node_ESQLFindPlayerRows::RemoveInputPin(UEdGraphPin* Pin)
{
	RemoveClauseForPin(Pin);
}

bool UK2Node_ESQLFindPlayerRows::CanRemovePin(const UEdGraphPin* Pin) const
{
	return Pin && IsQueryClausePinName(Pin->PinName);
}

void UK2Node_ESQLFindPlayerRows::AllocateOperationPins()
{
	UEdGraphPin* QuerySpecPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLQuerySpec::StaticStruct(), ESQLPlayerTypedK2NodePins::QuerySpec);
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(QuerySpecPin);
	QuerySpecPin->bHidden = true;
	AllocateQueryClausePins();
}

void UK2Node_ESQLFindPlayerRows::ExpandOperationPins(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node_CallFunction* FunctionNode)
{
	UEdGraphPin* FunctionQuerySpecPin = FunctionNode->FindPinChecked(ESQLPlayerTypedK2NodePins::QuerySpec);
	if (UEdGraphPin* QuerySpecPin = GetLegacyQuerySpecPin(); HasExplicitValue(QuerySpecPin))
	{
		MoveOrCopyPinToIntermediate(CompilerContext, QuerySpecPin, FunctionQuerySpecPin);
		return;
	}

	if (UEdGraphPin* BuiltQuerySpecPin = BuildQuerySpecPin(CompilerContext, SourceGraph))
	{
		BuiltQuerySpecPin->MakeLinkTo(FunctionQuerySpecPin);
	}
}

void UK2Node_ESQLFindPlayerRows::ValidateOperationPins(FCompilerResultsLog& MessageLog) const
{
	if (HasExplicitValue(GetLegacyQuerySpecPin()))
	{
		return;
	}

	ValidateQueryClausePins(MessageLog);
}

UEdGraphPin* UK2Node_ESQLFindPlayerRows::GetLegacyQuerySpecPin() const
{
	return UEdGraphNode::FindPin(ESQLPlayerTypedK2NodePins::QuerySpec);
}

void UK2Node_ESQLDeletePlayerRow::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* PlayerDBPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLPlayerDBComponent::StaticClass(), ESQLPlayerTypedK2NodePins::PlayerDBComponent);
	PlayerDBPin->PinFriendlyName = LOCTEXT("DeletePlayerDBFriendlyName", "Player DB");
	SetPinToolTip(*PlayerDBPin, LOCTEXT("DeletePlayerDBTooltip", "Explicit player database component that owns the player-scoped SQL data."));

	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), ESQLPlayerTypedK2NodePins::TableAsset);
	TableAssetPin->PinFriendlyName = LOCTEXT("DeletePlayerTableAssetFriendlyName", "Table Asset");
	SetPinToolTip(*TableAssetPin, LOCTEXT("DeletePlayerTableAssetTooltip", "The SQL table asset that owns the row schema being deleted."));

	UEdGraphPin* RowIdPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLId::StaticStruct(), ESQLPlayerTypedK2NodePins::RowId);
	RowIdPin->PinFriendlyName = LOCTEXT("DeletePlayerRowIdFriendlyName", "SQL Id");
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(RowIdPin);
	SetPinToolTip(*RowIdPin, LOCTEXT("DeletePlayerRowIdTooltip", "SQL identifier that provides the player row id value for the delete operation."));

	UEdGraphPin* ResultPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQueryResult::StaticStruct(), ESQLPlayerTypedK2NodePins::Result);
	ResultPin->PinFriendlyName = LOCTEXT("DeletePlayerResultFriendlyName", "Result");
	SetPinToolTip(*ResultPin, LOCTEXT("DeletePlayerResultTooltip", "Raw SQL query result for success state, rows, and error details."));

	Super::AllocateDefaultPins();
}

FText UK2Node_ESQLDeletePlayerRow::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const FText MenuTitle = LOCTEXT("DeletePlayerSQLRowMenuTitle", "Delete Player SQL Row");
	if (TitleType == ENodeTitleType::MenuTitle)
	{
		return MenuTitle;
	}

	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (TableAssetPin && TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject)
	{
		if (CachedNodeTitle.IsOutOfDate(this))
		{
			FFormatNamedArguments Args;
			Args.Add(TEXT("Title"), MenuTitle);
			Args.Add(TEXT("TableName"), FText::FromString(TableAssetPin->DefaultObject->GetName()));
			CachedNodeTitle.SetCachedText(FText::Format(LOCTEXT("DeletePlayerAssetAwareNodeTitle", "{Title} {TableName}"), Args), this);
		}

		return CachedNodeTitle;
	}

	return MenuTitle;
}

void UK2Node_ESQLDeletePlayerRow::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
	}
}

FText UK2Node_ESQLDeletePlayerRow::GetTooltipText() const
{
	return LOCTEXT("DeletePlayerSQLRowTooltip", "Deletes one row from a player-scoped SQL table through the runtime SQL bridge.");
}

void UK2Node_ESQLDeletePlayerRow::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* PlayerDBPin = GetPlayerDBPin();
	if (!PlayerDBPin || (PlayerDBPin->LinkedTo.Num() == 0 && PlayerDBPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingDeletePlayerDBOnExpand", "@@ must have a Player DB Component specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* TableAssetPin = GetTableAssetPin();
	if (!TableAssetPin || (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingDeletePlayerTableAssetOnExpand", "@@ must have a Table Asset specified.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* BridgeCallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	BridgeCallNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, DeletePlayerSQLRowById), UESQLBlueprintBridge::StaticClass());
	BridgeCallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *BridgeCallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *BridgeCallNode->GetThenPin());

	MoveOrCopyPinToIntermediate(CompilerContext, PlayerDBPin, BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::PlayerDBComponent));
	MoveOrCopyPinToIntermediate(CompilerContext, TableAssetPin, BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::TableAsset));
	MoveOrCopyPinToIntermediate(CompilerContext, GetRowIdPin(), BridgeCallNode->FindPinChecked(ESQLPlayerTypedK2NodePins::SqlId));
	CompilerContext.MovePinLinksToIntermediate(*GetQueryResultPin(), *BridgeCallNode->GetReturnValuePin());

	BreakAllNodeLinks();
}

FSlateIcon UK2Node_ESQLDeletePlayerRow::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = GetNodeTitleColor();
	return FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");
}

void UK2Node_ESQLDeletePlayerRow::PostReconstructNode()
{
	Super::PostReconstructNode();
}

void UK2Node_ESQLDeletePlayerRow::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (UEdGraphPin* TableAssetPin = GetTableAssetPin(&OldPins))
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	UpgradeLegacyStringRowIdPin(OldPins, ESQLPlayerTypedK2NodePins::RowId, GetRowIdPin(), Cast<UESQLTableAsset>(GetTableAssetPin() ? GetTableAssetPin()->DefaultObject : nullptr));
}

void UK2Node_ESQLDeletePlayerRow::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLDeletePlayerRow::GetMenuCategory() const
{
	return LOCTEXT("DeletePlayerSQLMenuCategory", "SQL|Player");
}

void UK2Node_ESQLDeletePlayerRow::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PlayerDBPin = GetPlayerDBPin();
	const UEdGraphPin* TableAssetPin = GetTableAssetPin();
	const UEdGraphPin* RowIdPin = GetRowIdPin();
	if (!PlayerDBPin || !TableAssetPin || !RowIdPin)
	{
		MessageLog.Error(*LOCTEXT("MissingDeletePlayerPinsError", "Missing pins in @@").ToString(), this);
		return;
	}

	if (PlayerDBPin->LinkedTo.Num() == 0 && PlayerDBPin->DefaultObject == nullptr)
	{
		MessageLog.Error(*LOCTEXT("NoDeletePlayerDBError", "No Player DB Component specified in @@").ToString(), this);
		return;
	}

	if (TableAssetPin->LinkedTo.Num() == 0 && TableAssetPin->DefaultObject == nullptr)
	{
		MessageLog.Error(*LOCTEXT("NoDeletePlayerTableAssetError", "No SQL Table Asset specified in @@").ToString(), this);
		return;
	}

	if (RowIdPin->LinkedTo.Num() == 0)
	{
		FESQLId SqlId;
		if (!TryGetSqlIdFromStructDefault(RowIdPin, SqlId))
		{
			MessageLog.Error(*LOCTEXT("MissingDeletePlayerRowIdError", "@@ requires an SQL Id when the pin is not linked.").ToString(), this);
		}
	}
}

void UK2Node_ESQLDeletePlayerRow::PreloadRequiredAssets()
{
	if (UEdGraphPin* TableAssetPin = GetTableAssetPin())
	{
		if (UESQLTableAsset* TableAsset = Cast<UESQLTableAsset>(TableAssetPin->DefaultObject))
		{
			PreloadObject(TableAsset);
		}
	}

	Super::PreloadRequiredAssets();
}

void UK2Node_ESQLDeletePlayerRow::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin == GetTableAssetPin())
	{
		CachedNodeTitle.Clear();
	}
}

UEdGraphPin* UK2Node_ESQLDeletePlayerRow::GetPlayerDBPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLPlayerTypedK2NodePins::PlayerDBComponent)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLDeletePlayerRow::GetTableAssetPin(const TArray<UEdGraphPin*>* PinsToSearch) const
{
	const TArray<UEdGraphPin*>* SearchPins = PinsToSearch ? PinsToSearch : &Pins;
	for (UEdGraphPin* Pin : *SearchPins)
	{
		if (Pin && Pin->PinName == ESQLPlayerTypedK2NodePins::TableAsset)
		{
			return Pin;
		}
	}

	return nullptr;
}

UEdGraphPin* UK2Node_ESQLDeletePlayerRow::GetRowIdPin() const
{
	return FindPinChecked(ESQLPlayerTypedK2NodePins::RowId);
}

UEdGraphPin* UK2Node_ESQLDeletePlayerRow::GetQueryResultPin() const
{
	return FindPinChecked(ESQLPlayerTypedK2NodePins::Result);
}

void UK2Node_ESQLDeletePlayerRow::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

#undef LOCTEXT_NAMESPACE