// Copyright Kemal Erdem YILMAZ. All Rights Reserved.

#include "K2Node/ESQLQueryBuilderK2Nodes.h"

#include "Blueprint/ESQLBlueprintBridge.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node/ESQLK2FieldFilterUtils.h"
#include "K2Node_CallFunction.h"
#include "K2Node_MakeArray.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Misc/DefaultValueHelper.h"
#include "ScopedTransaction.h"
#include "Shared/ESQLTypes.h"
#include "TableAsset/ESQLTableAsset.h"
#include "ToolMenu.h"
#include "ToolMenuSection.h"

#define LOCTEXT_NAMESPACE "ESQLQueryBuilderK2Nodes"

namespace
{
	const FName QueryBuilderTableAssetPinName(TEXT("TableAsset"));
	const FName QueryBuilderLimitPinName(TEXT("Limit"));
	const FName QueryBuilderOffsetPinName(TEXT("Offset"));
	const FName QueryBuilderOutputPinName(TEXT("QuerySpec"));

	constexpr TCHAR FilterFieldPrefix[] = TEXT("FilterFieldName_");
	constexpr TCHAR FilterOperationPrefix[] = TEXT("FilterOperation_");
	constexpr TCHAR FilterValuePrefix[] = TEXT("FilterValue_");
	constexpr TCHAR FilterValuesPrefix[] = TEXT("FilterValues_");
	constexpr TCHAR SortFieldPrefix[] = TEXT("SortFieldName_");
	constexpr TCHAR SortAscendingPrefix[] = TEXT("SortAscending_");

	void MoveOrCopyPinToIntermediate(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	}

	bool HasExplicitValue(const UEdGraphPin* Pin)
	{
		if (!Pin)
		{
			return false;
		}

		if (Pin->LinkedTo.Num() > 0)
		{
			return true;
		}

		return !Pin->DefaultValue.IsEmpty() && Pin->DefaultValue != Pin->AutogeneratedDefaultValue;
	}

	void ConfigureArrayNodeElementType(UK2Node_MakeArray* MakeArrayNode, const UScriptStruct* ElementStruct)
	{
		if (!MakeArrayNode || !ElementStruct)
		{
			return;
		}

		if (UEdGraphPin* OutputPin = MakeArrayNode->GetOutputPin())
		{
			OutputPin->PinType.ContainerType = EPinContainerType::Array;
			OutputPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Struct;
			OutputPin->PinType.PinSubCategory = NAME_None;
			OutputPin->PinType.PinSubCategoryObject = const_cast<UScriptStruct*>(ElementStruct);
		}

		for (UEdGraphPin* Pin : MakeArrayNode->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Input)
			{
				Pin->PinType.ContainerType = EPinContainerType::None;
				Pin->PinType.PinCategory = UEdGraphSchema_K2::PC_Struct;
				Pin->PinType.PinSubCategory = NAME_None;
				Pin->PinType.PinSubCategoryObject = const_cast<UScriptStruct*>(ElementStruct);
			}
		}
	}

	TArray<UEdGraphPin*> CollectInputPins(UK2Node_MakeArray* MakeArrayNode)
	{
		TArray<UEdGraphPin*> InputPins;
		if (!MakeArrayNode)
		{
			return InputPins;
		}

		for (UEdGraphPin* Pin : MakeArrayNode->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Input)
			{
				InputPins.Add(Pin);
			}
		}

		return InputPins;
	}

	bool TryGetLiteralFilterOperation(const UEdGraphPin* OperationPin, EESQLFilterOperation& OutOperation)
	{
		if (!OperationPin || OperationPin->LinkedTo.Num() > 0)
		{
			return false;
		}

		FString DefaultValue = OperationPin->GetDefaultAsString();
		DefaultValue.TrimStartAndEndInline();
		DefaultValue.RemoveFromStart(TEXT("\""));
		DefaultValue.RemoveFromEnd(TEXT("\""));
		if (DefaultValue.IsEmpty())
		{
			return false;
		}

		const UEnum* FilterOperationEnum = StaticEnum<EESQLFilterOperation>();
		if (FilterOperationEnum)
		{
			int64 EnumValue = FilterOperationEnum->GetValueByNameString(DefaultValue);
			if (EnumValue == INDEX_NONE)
			{
				EnumValue = FilterOperationEnum->GetValueByName(FName(*DefaultValue));
			}

			if (EnumValue == INDEX_NONE && DefaultValue.Contains(TEXT("::")))
			{
				FString UnqualifiedValue;
				DefaultValue.Split(TEXT("::"), nullptr, &UnqualifiedValue, ESearchCase::IgnoreCase, ESearchDir::FromEnd);
				EnumValue = FilterOperationEnum->GetValueByNameString(UnqualifiedValue);
			}

			if (EnumValue != INDEX_NONE)
			{
				OutOperation = static_cast<EESQLFilterOperation>(EnumValue);
				return true;
			}
		}

		int32 NumericValue = 0;
		if (FDefaultValueHelper::ParseInt(DefaultValue, NumericValue))
		{
			OutOperation = static_cast<EESQLFilterOperation>(NumericValue);
			return true;
		}

		return false;
	}
}

FName FESQLQueryClauseUiBase::GetQueryClauseTableAssetPinName() const
{
	return QueryBuilderTableAssetPinName;
}

FName FESQLQueryClauseUiBase::GetTableAssetPinName()
{
	return QueryBuilderTableAssetPinName;
}

FName FESQLQueryClauseUiBase::GetLimitPinName()
{
	return QueryBuilderLimitPinName;
}

FName FESQLQueryClauseUiBase::GetOffsetPinName()
{
	return QueryBuilderOffsetPinName;
}

FName FESQLQueryClauseUiBase::MakeFilterFieldPinName(int32 Index)
{
	return *FString::Printf(TEXT("%s%d"), FilterFieldPrefix, Index);
}

FName FESQLQueryClauseUiBase::MakeFilterOperationPinName(int32 Index)
{
	return *FString::Printf(TEXT("%s%d"), FilterOperationPrefix, Index);
}

FName FESQLQueryClauseUiBase::MakeFilterValuePinName(int32 Index)
{
	return *FString::Printf(TEXT("%s%d"), FilterValuePrefix, Index);
}

FName FESQLQueryClauseUiBase::MakeFilterValuesPinName(int32 Index)
{
	return *FString::Printf(TEXT("%s%d"), FilterValuesPrefix, Index);
}

FName FESQLQueryClauseUiBase::MakeSortFieldPinName(int32 Index)
{
	return *FString::Printf(TEXT("%s%d"), SortFieldPrefix, Index);
}

FName FESQLQueryClauseUiBase::MakeSortAscendingPinName(int32 Index)
{
	return *FString::Printf(TEXT("%s%d"), SortAscendingPrefix, Index);
}

FESQLQueryClauseUiBase::EClausePinKind FESQLQueryClauseUiBase::ParseClausePinName(const FName PinName, int32& OutIndex)
{
	OutIndex = INDEX_NONE;
	const FString PinNameString = PinName.ToString();

	auto MatchIndexedPrefix = [&PinNameString, &OutIndex](const TCHAR* Prefix) -> bool
	{
		const FString PrefixString(Prefix);
		if (!PinNameString.StartsWith(PrefixString))
		{
			return false;
		}

		const FString Suffix = PinNameString.RightChop(PrefixString.Len());
		if (Suffix.IsEmpty() || !Suffix.IsNumeric())
		{
			return false;
		}

		OutIndex = FCString::Atoi(*Suffix);
		return true;
	};

	if (MatchIndexedPrefix(FilterFieldPrefix))
	{
		return EClausePinKind::FilterField;
	}
	if (MatchIndexedPrefix(FilterOperationPrefix))
	{
		return EClausePinKind::FilterOperation;
	}
	if (MatchIndexedPrefix(FilterValuePrefix))
	{
		return EClausePinKind::FilterValue;
	}
	if (MatchIndexedPrefix(FilterValuesPrefix))
	{
		return EClausePinKind::FilterValues;
	}
	if (MatchIndexedPrefix(SortFieldPrefix))
	{
		return EClausePinKind::SortField;
	}
	if (MatchIndexedPrefix(SortAscendingPrefix))
	{
		return EClausePinKind::SortAscending;
	}

	return EClausePinKind::None;
}

bool FESQLQueryClauseUiBase::IsFieldNamePinName(const FName PinName)
{
	int32 ClauseIndex = INDEX_NONE;
	const EClausePinKind ClauseKind = ParseClausePinName(PinName, ClauseIndex);
	return ClauseKind == EClausePinKind::FilterField || ClauseKind == EClausePinKind::SortField;
}

FESQLQueryClauseUiBase::EClausePinKind FESQLQueryClauseUiBase::DescribeClausePinName(const FName PinName, int32& OutIndex)
{
	return ParseClausePinName(PinName, OutIndex);
}

bool FESQLQueryClauseUiBase::UsesMultiValuePins(const UEdGraphPin* OperationPin)
{
	EESQLFilterOperation LiteralOperation = EESQLFilterOperation::Equal;
	return TryGetLiteralFilterOperation(OperationPin, LiteralOperation) && LiteralOperation == EESQLFilterOperation::In;
}

bool FESQLQueryClauseUiBase::IsValuePinName(const FName PinName)
{
	int32 ClauseIndex = INDEX_NONE;
	return ParseClausePinName(PinName, ClauseIndex) == EClausePinKind::FilterValue;
}

bool FESQLQueryClauseUiBase::IsValuesPinName(const FName PinName)
{
	int32 ClauseIndex = INDEX_NONE;
	return ParseClausePinName(PinName, ClauseIndex) == EClausePinKind::FilterValues;
}

bool FESQLQueryClauseUiBase::IsQueryClausePinName(const FName PinName)
{
	int32 ClauseIndex = INDEX_NONE;
	return ParseClausePinName(PinName, ClauseIndex) != EClausePinKind::None;
}

UEdGraphPin* FESQLQueryClauseUiBase::FindPinChecked(FName PinName) const
{
	return GetQueryClauseNode()->FindPinChecked(PinName);
}

UEdGraphPin* FESQLQueryClauseUiBase::FindPin(FName PinName) const
{
	return GetQueryClauseNode()->FindPin(PinName);
}

void FESQLQueryClauseUiBase::SetPinToolTip(UEdGraphPin& Pin, const FText& Description) const
{
	Pin.PinToolTip = UEdGraphSchema_K2::TypeToText(Pin.PinType).ToString();
	if (const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>())
	{
		Pin.PinToolTip += TEXT(" ");
		Pin.PinToolTip += K2Schema->GetPinDisplayName(&Pin).ToString();
	}
	Pin.PinToolTip += TEXT("\n");
	Pin.PinToolTip += Description.ToString();
}

void FESQLQueryClauseUiBase::AddClausePinsForIndex(int32 Index)
{
	UK2Node* Node = GetQueryClauseNode();
	check(Node);

	UEdGraphPin* FieldNamePin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, MakeFilterFieldPinName(Index));
	FieldNamePin->PinFriendlyName = FText::Format(LOCTEXT("FilterFieldFriendlyName", "Filter {0} Field Name"), FText::AsNumber(Index + 1));
	SetPinToolTip(*FieldNamePin, LOCTEXT("FilterFieldTooltip", "Field on the SQL row struct used for this filter clause."));

	UEdGraphPin* OperationPin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StaticEnum<EESQLFilterOperation>(), MakeFilterOperationPinName(Index));
	OperationPin->PinFriendlyName = FText::Format(LOCTEXT("FilterOperationFriendlyName", "Filter {0} Operation"), FText::AsNumber(Index + 1));
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(OperationPin);
	SetPinToolTip(*OperationPin, LOCTEXT("FilterOperationTooltip", "Comparison operation used for this filter clause."));

	UEdGraphPin* ValuePin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLBindingValue::StaticStruct(), MakeFilterValuePinName(Index));
	ValuePin->PinFriendlyName = FText::Format(LOCTEXT("FilterValueFriendlyName", "Filter {0} Value"), FText::AsNumber(Index + 1));
	SetPinToolTip(*ValuePin, LOCTEXT("FilterValueTooltip", "Primary comparison value. With a literal table asset and field selected, this pin retargets to that field type."));

	UEdGraphNode::FCreatePinParams ValuesPinParams;
	ValuesPinParams.ContainerType = EPinContainerType::Array;
	UEdGraphPin* ValuesPin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FESQLBindingValue::StaticStruct(), MakeFilterValuesPinName(Index), ValuesPinParams);
	ValuesPin->PinFriendlyName = FText::Format(LOCTEXT("FilterValuesFriendlyName", "Filter {0} Values"), FText::AsNumber(Index + 1));
	ValuesPin->bAdvancedView = true;
	SetPinToolTip(*ValuesPin, LOCTEXT("FilterValuesTooltip", "Optional binding-value array used for multi-value operations such as IN."));
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(ValuesPin);
}

void FESQLQueryClauseUiBase::AddSortPinsForIndex(int32 Index)
{
	UK2Node* Node = GetQueryClauseNode();
	check(Node);

	UEdGraphPin* FieldNamePin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, MakeSortFieldPinName(Index));
	FieldNamePin->PinFriendlyName = FText::Format(LOCTEXT("SortFieldFriendlyName", "Sort {0} Field Name"), FText::AsNumber(Index + 1));
	SetPinToolTip(*FieldNamePin, LOCTEXT("SortFieldTooltip", "Field on the SQL row struct used for this sort rule."));

	UEdGraphPin* AscendingPin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, MakeSortAscendingPinName(Index));
	AscendingPin->PinFriendlyName = FText::Format(LOCTEXT("SortAscendingFriendlyName", "Sort {0} Ascending"), FText::AsNumber(Index + 1));
	AscendingPin->DefaultValue = TEXT("true");
	AscendingPin->AutogeneratedDefaultValue = TEXT("true");
	SetPinToolTip(*AscendingPin, LOCTEXT("SortAscendingTooltip", "Whether this sort rule is ascending (true) or descending (false)."));
}

void FESQLQueryClauseUiBase::AllocateQueryClausePins()
{
	UK2Node* Node = GetQueryClauseNode();
	check(Node);

	for (int32 Index = 0; Index < GetQueryClauseUiState().NumFilterClauses; ++Index)
	{
		AddClausePinsForIndex(Index);
	}

	for (int32 Index = 0; Index < GetQueryClauseUiState().NumSortClauses; ++Index)
	{
		AddSortPinsForIndex(Index);
	}

	UEdGraphPin* LimitPin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, QueryBuilderLimitPinName);
	LimitPin->PinFriendlyName = LOCTEXT("QueryLimitFriendlyName", "Limit");
	LimitPin->bAdvancedView = true;
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(LimitPin);
	SetPinToolTip(*LimitPin, LOCTEXT("QueryLimitTooltip", "Optional maximum number of rows returned by the query spec."));

	UEdGraphPin* OffsetPin = Node->CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, QueryBuilderOffsetPinName);
	OffsetPin->PinFriendlyName = LOCTEXT("QueryOffsetFriendlyName", "Offset");
	OffsetPin->bAdvancedView = true;
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(OffsetPin);
	SetPinToolTip(*OffsetPin, LOCTEXT("QueryOffsetTooltip", "Optional row offset applied before returning results."));
}

void FESQLQueryClauseUiBase::RefreshQueryClausePinTypes() const
{
	for (int32 Index = 0; Index < GetQueryClauseUiState().NumFilterClauses; ++Index)
	{
		if (UEdGraphPin* ValuePin = FindPin(MakeFilterValuePinName(Index)))
		{
			ESQLK2FieldFilterUtils::ApplyFieldValuePinType(*ValuePin, ESQLK2FieldFilterUtils::ResolveLiteralFieldProperty(GetQueryClauseNode(), GetQueryClauseTableAssetPinName(), MakeFilterFieldPinName(Index)));
		}
	}
}

void FESQLQueryClauseUiBase::ValidateQueryClausePins(FCompilerResultsLog& MessageLog) const
{
	for (int32 Index = 0; Index < GetQueryClauseUiState().NumFilterClauses; ++Index)
	{
		const UEdGraphPin* FieldPin = FindPin(MakeFilterFieldPinName(Index));
		if (FieldPin && FieldPin->LinkedTo.Num() == 0 && FieldPin->GetDefaultAsString().TrimStartAndEnd().IsEmpty())
		{
			MessageLog.Error(*LOCTEXT("MissingQueryFilterFieldName", "@@ requires a Field Name for each filter clause when that pin is not linked.").ToString(), GetQueryClauseNode());
			return;
		}

		const UEdGraphPin* OperationPin = FindPin(MakeFilterOperationPinName(Index));
		const UEdGraphPin* ValuePin = FindPin(MakeFilterValuePinName(Index));
		const UEdGraphPin* ValuesPin = FindPin(MakeFilterValuesPinName(Index));

		EESQLFilterOperation LiteralOperation = EESQLFilterOperation::Equal;
		if (TryGetLiteralFilterOperation(OperationPin, LiteralOperation))
		{
			if (LiteralOperation == EESQLFilterOperation::In)
			{
				if (!HasExplicitValue(ValuePin) && !HasExplicitValue(ValuesPin))
				{
					MessageLog.Error(*LOCTEXT("MissingQueryInFilterValue", "@@ requires at least one Value or Values entry for each In filter clause.").ToString(), GetQueryClauseNode());
					return;
				}
			}
			else if (ValuesPin && HasExplicitValue(ValuesPin))
			{
				MessageLog.Error(*LOCTEXT("UnexpectedQueryValuesPin", "@@ only uses the Values pin for In filter clauses. Clear Values or switch the filter operation to In.").ToString(), GetQueryClauseNode());
				return;
			}
		}
	}

	for (int32 Index = 0; Index < GetQueryClauseUiState().NumSortClauses; ++Index)
	{
		const UEdGraphPin* FieldPin = FindPin(MakeSortFieldPinName(Index));
		if (FieldPin && FieldPin->LinkedTo.Num() == 0 && FieldPin->GetDefaultAsString().TrimStartAndEnd().IsEmpty())
		{
			MessageLog.Error(*LOCTEXT("MissingQuerySortFieldName", "@@ requires a Field Name for each sort clause when that pin is not linked.").ToString(), GetQueryClauseNode());
			return;
		}
	}

	auto ValidateNonNegativePin = [this, &MessageLog](const UEdGraphPin* Pin, const FText& ErrorText)
	{
		if (!Pin || Pin->LinkedTo.Num() > 0)
		{
			return false;
		}

		int32 ParsedValue = 0;
		if (!FDefaultValueHelper::ParseInt(Pin->GetDefaultAsString(), ParsedValue))
		{
			ParsedValue = FCString::Atoi(*Pin->GetDefaultAsString());
		}

		if (ParsedValue < 0)
		{
			MessageLog.Error(*ErrorText.ToString(), GetQueryClauseNode());
			return true;
		}

		return false;
	};

	if (ValidateNonNegativePin(FindLimitPin(), LOCTEXT("InvalidQueryLimit", "@@ requires Limit to be zero or greater when the pin is not linked.")))
	{
		return;
	}

	ValidateNonNegativePin(FindOffsetPin(), LOCTEXT("InvalidQueryOffset", "@@ requires Offset to be zero or greater when the pin is not linked."));
}

void FESQLQueryClauseUiBase::ReconstructClauseNode(const FText& TransactionText)
{
	UK2Node* Node = GetQueryClauseNode();
	if (!Node)
	{
		return;
	}

	const FScopedTransaction Transaction(TransactionText);
	Node->Modify();
	if (UEdGraph* Graph = Node->GetGraph())
	{
		Graph->Modify();
	}

	Node->ReconstructNode();
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(Node))
	{
		FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(Blueprint);
	}
	Node->GetGraph()->NotifyGraphChanged();
}

void FESQLQueryClauseUiBase::AddFilterClause()
{
	if (GetQueryClauseUiState().NumFilterClauses >= MaxClauseCount)
	{
		return;
	}

	++GetQueryClauseUiState().NumFilterClauses;
	ReconstructClauseNode(LOCTEXT("AddSQLQueryFilterClause", "Add SQL Query Filter Clause"));
}

void FESQLQueryClauseUiBase::AddSortClause()
{
	if (GetQueryClauseUiState().NumSortClauses >= MaxClauseCount)
	{
		return;
	}

	++GetQueryClauseUiState().NumSortClauses;
	ReconstructClauseNode(LOCTEXT("AddSQLQuerySortClause", "Add SQL Query Sort Clause"));
}

void FESQLQueryClauseUiBase::RemoveClauseForPin(UEdGraphPin* Pin)
{
	if (!Pin)
	{
		return;
	}

	int32 ClauseIndex = INDEX_NONE;
	const EClausePinKind ClauseKind = ParseClausePinName(Pin->PinName, ClauseIndex);
	if (ClauseKind == EClausePinKind::None || ClauseIndex == INDEX_NONE)
	{
		return;
	}

	if ((ClauseKind == EClausePinKind::FilterField || ClauseKind == EClausePinKind::FilterOperation || ClauseKind == EClausePinKind::FilterValue || ClauseKind == EClausePinKind::FilterValues)
		&& GetQueryClauseUiState().NumFilterClauses > 0)
	{
		--GetQueryClauseUiState().NumFilterClauses;
	}
	else if ((ClauseKind == EClausePinKind::SortField || ClauseKind == EClausePinKind::SortAscending) && GetQueryClauseUiState().NumSortClauses > 0)
	{
		--GetQueryClauseUiState().NumSortClauses;
	}
	else
	{
		return;
	}

	ReconstructClauseNode(LOCTEXT("RemoveSQLQueryClause", "Remove SQL Query Clause"));
}

void FESQLQueryClauseUiBase::GetQueryClauseContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	if (!Menu || !Context || Context->bIsDebugging)
	{
		return;
	}

	FToolMenuSection& Section = Menu->AddSection(TEXT("ESQLQueryBuilder"), LOCTEXT("SQLQueryBuilderSection", "SQL Query"));

	Section.AddMenuEntry(
		TEXT("AddSQLQueryFilterClause"),
		LOCTEXT("AddSQLQueryFilterClauseLabel", "Add Filter Clause"),
		LOCTEXT("AddSQLQueryFilterClauseTooltip", "Add another SQL query filter clause."),
		FSlateIcon(),
		FUIAction(
			FExecuteAction::CreateLambda([this]()
			{
				const_cast<FESQLQueryClauseUiBase*>(this)->AddFilterClause();
			}),
			FCanExecuteAction::CreateLambda([this]()
			{
				return GetQueryClauseUiState().NumFilterClauses < MaxClauseCount;
			})
		)
	);

	Section.AddMenuEntry(
		TEXT("AddSQLQuerySortClause"),
		LOCTEXT("AddSQLQuerySortClauseLabel", "Add Sort Rule"),
		LOCTEXT("AddSQLQuerySortClauseTooltip", "Add another SQL query sort rule."),
		FSlateIcon(),
		FUIAction(
			FExecuteAction::CreateLambda([this]()
			{
				const_cast<FESQLQueryClauseUiBase*>(this)->AddSortClause();
			}),
			FCanExecuteAction::CreateLambda([this]()
			{
				return GetQueryClauseUiState().NumSortClauses < MaxClauseCount;
			})
		)
	);

	if (Context->Pin && IsQueryClausePinName(Context->Pin->PinName))
	{
		Section.AddMenuEntry(
			TEXT("RemoveSQLQueryClause"),
			LOCTEXT("RemoveSQLQueryClauseLabel", "Remove Clause"),
			LOCTEXT("RemoveSQLQueryClauseTooltip", "Remove the filter or sort clause that owns this pin."),
			FSlateIcon(),
			FUIAction(FExecuteAction::CreateLambda([this, Pin = Context->Pin]()
			{
				const_cast<FESQLQueryClauseUiBase*>(this)->RemoveClauseForPin(const_cast<UEdGraphPin*>(Pin));
			}))
		);
	}
}

UEdGraphPin* FESQLQueryClauseUiBase::FindLimitPin() const
{
	return FindPin(QueryBuilderLimitPinName);
}

UEdGraphPin* FESQLQueryClauseUiBase::FindOffsetPin() const
{
	return FindPin(QueryBuilderOffsetPinName);
}

UEdGraphPin* FESQLQueryClauseUiBase::BuildFilterPin(int32 Index, FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	UK2Node_CallFunction* MakeFilterNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(GetQueryClauseNode(), SourceGraph);
	MakeFilterNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, MakeSQLFieldFilter), UESQLBlueprintBridge::StaticClass());
	MakeFilterNode->AllocateDefaultPins();

	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(MakeFilterFieldPinName(Index)), MakeFilterNode->FindPinChecked(TEXT("FieldName")));
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(MakeFilterOperationPinName(Index)), MakeFilterNode->FindPinChecked(TEXT("Operation")));
	ESQLK2FieldFilterUtils::MoveValuePinToBindingPin(CompilerContext, SourceGraph, GetQueryClauseNode(), FindPinChecked(MakeFilterValuePinName(Index)), MakeFilterNode->FindPinChecked(TEXT("Value")));

	if (UEdGraphPin* ValuesPin = FindPin(MakeFilterValuesPinName(Index)); ValuesPin && HasExplicitValue(ValuesPin))
	{
		MoveOrCopyPinToIntermediate(CompilerContext, ValuesPin, MakeFilterNode->FindPinChecked(TEXT("Values")));
	}

	return MakeFilterNode->GetReturnValuePin();
}

UEdGraphPin* FESQLQueryClauseUiBase::BuildSortPin(int32 Index, FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	UK2Node_CallFunction* MakeSortNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(GetQueryClauseNode(), SourceGraph);
	MakeSortNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, MakeSQLSortRule), UESQLBlueprintBridge::StaticClass());
	MakeSortNode->AllocateDefaultPins();

	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(MakeSortFieldPinName(Index)), MakeSortNode->FindPinChecked(TEXT("FieldName")));
	MoveOrCopyPinToIntermediate(CompilerContext, FindPinChecked(MakeSortAscendingPinName(Index)), MakeSortNode->FindPinChecked(TEXT("bAscending")));
	return MakeSortNode->GetReturnValuePin();
}

UEdGraphPin* FESQLQueryClauseUiBase::BuildFilterArrayPin(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	const int32 ClauseCount = GetQueryClauseUiState().NumFilterClauses;
	if (ClauseCount <= 0)
	{
		return nullptr;
	}

	UK2Node_MakeArray* MakeArrayNode = CompilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(GetQueryClauseNode(), SourceGraph);
	MakeArrayNode->AllocateDefaultPins();
	for (int32 Index = 1; Index < ClauseCount; ++Index)
	{
		MakeArrayNode->AddInputPin();
	}
	ConfigureArrayNodeElementType(MakeArrayNode, FESQLFieldFilter::StaticStruct());

	const TArray<UEdGraphPin*> InputPins = CollectInputPins(MakeArrayNode);
	for (int32 Index = 0; Index < ClauseCount && Index < InputPins.Num(); ++Index)
	{
		if (UEdGraphPin* FilterPin = BuildFilterPin(Index, CompilerContext, SourceGraph))
		{
			FilterPin->MakeLinkTo(InputPins[Index]);
		}
	}

	return MakeArrayNode->GetOutputPin();
}

UEdGraphPin* FESQLQueryClauseUiBase::BuildSortArrayPin(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	const int32 ClauseCount = GetQueryClauseUiState().NumSortClauses;
	if (ClauseCount <= 0)
	{
		return nullptr;
	}

	UK2Node_MakeArray* MakeArrayNode = CompilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(GetQueryClauseNode(), SourceGraph);
	MakeArrayNode->AllocateDefaultPins();
	for (int32 Index = 1; Index < ClauseCount; ++Index)
	{
		MakeArrayNode->AddInputPin();
	}
	ConfigureArrayNodeElementType(MakeArrayNode, FESQLSortRule::StaticStruct());

	const TArray<UEdGraphPin*> InputPins = CollectInputPins(MakeArrayNode);
	for (int32 Index = 0; Index < ClauseCount && Index < InputPins.Num(); ++Index)
	{
		if (UEdGraphPin* SortPin = BuildSortPin(Index, CompilerContext, SourceGraph))
		{
			SortPin->MakeLinkTo(InputPins[Index]);
		}
	}

	return MakeArrayNode->GetOutputPin();
}

UEdGraphPin* FESQLQueryClauseUiBase::BuildQuerySpecPin(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	UK2Node_CallFunction* MakeQuerySpecNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(GetQueryClauseNode(), SourceGraph);
	MakeQuerySpecNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UESQLBlueprintBridge, MakeSQLQuerySpec), UESQLBlueprintBridge::StaticClass());
	MakeQuerySpecNode->AllocateDefaultPins();

	if (UEdGraphPin* FiltersArrayPin = BuildFilterArrayPin(CompilerContext, SourceGraph))
	{
		FiltersArrayPin->MakeLinkTo(MakeQuerySpecNode->FindPinChecked(TEXT("Filters")));
	}

	if (UEdGraphPin* SortArrayPin = BuildSortArrayPin(CompilerContext, SourceGraph))
	{
		SortArrayPin->MakeLinkTo(MakeQuerySpecNode->FindPinChecked(TEXT("SortRules")));
	}

	MoveOrCopyPinToIntermediate(CompilerContext, FindLimitPin(), MakeQuerySpecNode->FindPinChecked(TEXT("Limit")));
	MoveOrCopyPinToIntermediate(CompilerContext, FindOffsetPin(), MakeQuerySpecNode->FindPinChecked(TEXT("Offset")));
	return MakeQuerySpecNode->GetReturnValuePin();
}

void UK2Node_ESQLMakeQuerySpec::AllocateDefaultPins()
{
	UEdGraphPin* TableAssetPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESQLTableAsset::StaticClass(), QueryBuilderTableAssetPinName);
	TableAssetPin->PinFriendlyName = LOCTEXT("QueryBuilderTableAssetFriendlyName", "Table Asset");
	TableAssetPin->bAdvancedView = true;
	TableAssetPin->PinToolTip = LOCTEXT("QueryBuilderTableAssetTooltip", "Optional SQL table asset used to drive field-name dropdowns and typed filter value pins.").ToString();

	AllocateQueryClausePins();

	UEdGraphPin* OutputPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Struct, FESQLQuerySpec::StaticStruct(), QueryBuilderOutputPinName);
	OutputPin->PinFriendlyName = LOCTEXT("QueryBuilderOutputFriendlyName", "Query Spec");
	OutputPin->PinToolTip = LOCTEXT("QueryBuilderOutputTooltip", "Structured SQL query specification built from the configured filter and sort clauses.").ToString();

	Super::AllocateDefaultPins();
	RefreshQueryClausePinTypes();
}

FText UK2Node_ESQLMakeQuerySpec::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	return LOCTEXT("MakeSQLQuerySpecNodeTitle", "Make SQL Query Spec");
}

FText UK2Node_ESQLMakeQuerySpec::GetTooltipText() const
{
	return LOCTEXT("MakeSQLQuerySpecNodeTooltip", "Builds an SQL query spec from reusable filter clauses, sort rules, limit, and offset settings.");
}

void UK2Node_ESQLMakeQuerySpec::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	if (UEdGraphPin* OutputPin = GetQuerySpecPin())
	{
		if (UEdGraphPin* BuiltQuerySpecPin = BuildQuerySpecPin(CompilerContext, SourceGraph))
		{
			CompilerContext.MovePinLinksToIntermediate(*OutputPin, *BuiltQuerySpecPin);
		}
	}

	BreakAllNodeLinks();
}

void UK2Node_ESQLMakeQuerySpec::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLMakeQuerySpec::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLMakeQuerySpec::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshQueryClausePinTypes();
}

void UK2Node_ESQLMakeQuerySpec::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	if (GetClass()->HasMetaData(TEXT("ESQLHideFromBlueprintPalette")))
	{
		return;
	}

	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

FText UK2Node_ESQLMakeQuerySpec::GetMenuCategory() const
{
	return LOCTEXT("MakeSQLQuerySpecMenuCategory", "SQL|Query");
}

void UK2Node_ESQLMakeQuerySpec::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);
	GetQueryClauseContextMenuActions(Menu, Context);
}

void UK2Node_ESQLMakeQuerySpec::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);
	ValidateQueryClausePins(MessageLog);
}

void UK2Node_ESQLMakeQuerySpec::AddInputPin()
{
	AddFilterClause();
}

bool UK2Node_ESQLMakeQuerySpec::CanAddPin() const
{
	return ClauseUiState.NumFilterClauses < MaxClauseCount;
}

void UK2Node_ESQLMakeQuerySpec::RemoveInputPin(UEdGraphPin* Pin)
{
	RemoveClauseForPin(Pin);
}

bool UK2Node_ESQLMakeQuerySpec::CanRemovePin(const UEdGraphPin* Pin) const
{
	if (!Pin)
	{
		return false;
	}

	return IsQueryClausePinName(Pin->PinName);
}

UEdGraphPin* UK2Node_ESQLMakeQuerySpec::GetTableAssetPin() const
{
	return UEdGraphNode::FindPin(QueryBuilderTableAssetPinName);
}

UEdGraphPin* UK2Node_ESQLMakeQuerySpec::GetQuerySpecPin() const
{
	return UEdGraphNode::FindPin(QueryBuilderOutputPinName);
}

#undef LOCTEXT_NAMESPACE