#!/usr/bin/env python3
"""Generate the complete frozen HTML color table consumed by the Slate style set."""

from __future__ import annotations

import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PLUGIN_ROOT = SCRIPT_DIR.parents[1]
MANIFEST = PLUGIN_ROOT / "Tests" / "Parity" / "BacklotReferenceManifest.json"
OUTPUT = (
    PLUGIN_ROOT
    / "Source"
    / "UnrealExtendedAtlassianEditor"
    / "Generated"
    / "ExtendedAtlassianPalette.inl"
)


def main() -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    colors = manifest["visualTokens"]["hexColors"]
    lines = [
        "// Generated by Tools/Parity/generate_backlot_palette.py. Do not hand-edit.",
    ]
    for color in colors:
        token = color[1:].upper()
        lines.append(
            f'{{ TEXT("Backlot.Literal.{token}"), TEXT("{color.lower()}") }},'
        )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT} ({len(colors)} colors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
