#!/usr/bin/env python3
"""Generate the complete frozen HTML geometry contract consumed by the Slate style set.

Three token families are emitted:

* ``Backlot.Metric.*``      - the named geometry the visual contract calls out by name.
* ``Backlot.HTML.Metric.*`` - every dimension literal in the source, grouped by CSS
  property, so no authored size can be quietly dropped.
* ``Backlot.HTML.Shadow.*`` - the authored box-shadow offsets, blurs, spreads and alphas.

Slate has no box-shadow or letter-spacing shorthand, so each is decomposed into the
scalar components ``SBacklotDropShadow`` and the text styles actually consume.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PLUGIN_ROOT = SCRIPT_DIR.parents[1]
MANIFEST = PLUGIN_ROOT / "Tests" / "Parity" / "BacklotReferenceManifest.json"
OUTPUT = (
    PLUGIN_ROOT
    / "Source"
    / "UnrealExtendedAtlassianEditor"
    / "Generated"
    / "ExtendedAtlassianMetrics.inl"
)

# CSS permits a bare leading decimal point, as in `.06em` and `-.012em`.
LENGTH = re.compile(r"(-?(?:\d+(?:\.\d+)?|\.\d+))(px|vh|vw|ch|em)?")
RGBA = re.compile(r"(?i)rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([0-9.]+)\s*)?\)")


def cpp_float(value: float) -> str:
    """Format a finite CSS number as a valid C++ float literal."""
    rendered = f"{value:g}"
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return rendered + "f"


def token(value: str) -> str:
    """Turn a CSS value into a stable, C-identifier-safe token suffix.

    A leading minus becomes `Neg` so `-.012em` and `.012em` stay distinct tokens.
    """
    normalized = value.strip()
    prefix = "Neg" if normalized.startswith("-") else ""
    cleaned = re.sub(r"[^0-9A-Za-z]+", "_", normalized).strip("_")
    return (prefix + cleaned) if cleaned else (prefix + "Zero")


def shadow_components(value: str) -> dict[str, float]:
    """Split `0 14px 34px rgba(0,0,0,.5)` into Slate-consumable scalars."""
    color = RGBA.search(value)
    alpha = 1.0
    red = green = blue = 0.0
    if color:
        red = float(color.group(1))
        green = float(color.group(2))
        blue = float(color.group(3))
        alpha = float(color.group(4)) if color.group(4) is not None else 1.0
    lengths = [
        float(match.group(1))
        for match in LENGTH.finditer(RGBA.sub("", value))
        if match.group(0).strip()
    ]
    while len(lengths) < 4:
        lengths.append(0.0)
    return {
        "OffsetX": lengths[0],
        "OffsetY": lengths[1],
        "Blur": lengths[2],
        "Spread": lengths[3],
        "R": red,
        "G": green,
        "B": blue,
        "A": alpha,
    }


def generate(manifest_path: Path) -> str:
    contract = json.loads(manifest_path.read_text(encoding="utf-8"))
    tokens = contract["visualTokens"]
    rows: list[str] = [
        "// Generated by Tools/Parity/generate_backlot_metrics.py. Do not hand-edit.",
        "",
        "// Named geometry required by the visual contract.",
    ]

    for name, value in tokens["namedMetrics"].items():
        rows.append(
            f'Style->Set(TEXT("Backlot.Metric.{name}"), {cpp_float(float(value))});'
        )

    rows.append("")
    rows.append("// Every dimension literal in the frozen source, grouped by property.")
    for prop, values in tokens["dimensions"].items():
        for value in values:
            rows.append(
                f'Style->Set(TEXT("Backlot.HTML.Metric.{token(prop)}.{token(value)}"), '
                f"{cpp_float(primary_length(value))});"
            )

    rows.append("")
    rows.append("// Authored drop shadows decomposed into Slate drawing parameters.")
    for index, shadow in enumerate(tokens["boxShadows"]):
        parts = shadow_components(shadow)
        for component, value in parts.items():
            rows.append(
                f'Style->Set(TEXT("Backlot.HTML.Shadow.{index:03d}.{component}"), '
                f"{cpp_float(value)});"
            )

    rows.append("")
    rows.append("// Authored letter-spacing tracking, in Slate 1/1000 em units.")
    for spacing in tokens["letterSpacings"]:
        match = LENGTH.match(spacing.strip())
        em = float(match.group(1)) if match else 0.0
        rows.append(
            f'Style->Set(TEXT("Backlot.HTML.Tracking.{token(spacing)}"), '
            f"{cpp_float(em * 1000.0)});"
        )

    return "\n".join(rows) + "\n"


def primary_length(value: str) -> float:
    """Return the first numeric length in a CSS value, ignoring units and functions."""
    match = LENGTH.search(value)
    return float(match.group(1)) if match else 0.0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=MANIFEST)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()

    generated = generate(args.manifest)
    if args.verify_only:
        if (
            not args.output.is_file()
            or args.output.read_text(encoding="utf-8") != generated
        ):
            print(f"error: generated metrics are stale: {args.output}")
            return 1
        print(f"Verified {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({generated.count('Style->Set')} metric tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
