#!/usr/bin/env python3
"""Generate every literal IBM Plex font/line-height contract used by the frozen HTML."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SHORTHAND = re.compile(
    r"^(?P<weight>400|500|600) "
    r"(?P<size>[0-9.]+)px/(?P<line>[0-9.]+) "
    r"'IBM Plex (?P<family>Sans|Mono)'"
)


def cpp_float(value: float) -> str:
    """Format a finite CSS number as a valid C++ float literal."""
    rendered = f"{value:g}"
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return rendered + "f"


def generate(manifest: Path) -> str:
    contract = json.loads(manifest.read_text(encoding="utf-8"))
    rows: list[str] = [
        "// Generated by Tools/Parity/generate_backlot_typography.py. Do not edit.",
    ]
    for index, shorthand in enumerate(contract["visualTokens"]["fontShorthands"]):
        match = SHORTHAND.match(shorthand)
        if not match:
            raise ValueError(f"Unsupported font shorthand: {shorthand}")
        family = "IBMPlex" + match.group("family")
        weight = {"400": "Regular", "500": "Medium", "600": "SemiBold"}[
            match.group("weight")
        ]
        size = float(match.group("size"))
        line_height = float(match.group("line"))
        rows.append(
            f'Style->Set(TEXT("Backlot.HTML.Font.{index:03d}"), '
            f'Text(Style, TEXT("{family}"), TEXT("{weight}"), '
            f'{cpp_float(size)}, TextColor));'
        )
        rows.append(
            f'Style->Set(TEXT("Backlot.HTML.LineHeight.{index:03d}"), '
            f'{cpp_float(line_height)});'
        )
    return "\n".join(rows) + "\n"


def main() -> int:
    script = Path(__file__).resolve()
    plugin = script.parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=plugin / "Tests" / "Parity" / "BacklotReferenceManifest.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=(
            plugin
            / "Source"
            / "UnrealExtendedAtlassianEditor"
            / "Generated"
            / "ExtendedAtlassianTypography.inl"
        ),
    )
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()

    generated = generate(args.manifest)
    if args.verify_only:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != generated:
            print(f"error: generated typography is stale: {args.output}")
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8", newline="\n")
        print(f"Wrote {args.output} (79 font contracts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
